# Generated by Django 4.2.11 on 2025-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(
                fields=["status", "-updated_at"], name="search_sess_status_1233c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(
                fields=["owner", "status"], name="search_sess_owner_i_17a010_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(
                fields=["updated_at"], name="search_sess_updated_52d095_idx"
            ),
        ),
    ]
