# Generated by Django 4.2.11 on 2025-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(
                fields=["owner", "status", "-updated_at"],
                name="session_owner_status_idx",
            ),
        ),
    ]
