# Generated by Django 4.2.11 on 2025-08-13 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="searchsession",
            name="session_owner_status_idx",
        ),
    ]
