# Generated by Django 4.2.11 on 2025-08-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0005_alter_sessionactivity_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Session Created"),
                    ("status_changed", "Status Changed"),
                    ("search_defined", "Search Defined"),
                    ("search_executed", "Search Executed"),
                    ("results_processed", "Results Processed"),
                    ("review_started", "Review Started"),
                    ("review_completed", "Review Completed"),
                    ("exported", "Data Exported"),
                    ("shared", "Session Shared"),
                    ("note_added", "Note Added"),
                    ("settings_changed", "Settings Changed"),
                    ("auto_execution", "Automatic Execution"),
                    ("execution_started", "Execution Started"),
                    ("execution_failed", "Execution Failed"),
                    ("processing_failed", "Processing Failed"),
                    ("transition_failed", "Transition Failed"),
                    ("manual_recovery", "Manual Recovery"),
                    ("auto_recovery", "Automatic Recovery"),
                    ("api_recovery", "API Recovery"),
                    ("recovery_action", "Recovery Action"),
                    ("search_started", "Search Started"),
                    ("state_change", "State Change"),
                    ("state_transition", "State Transition"),
                    ("status_change", "Status Change"),
                    ("state_reconciliation", "State Reconciliation"),
                    ("backwards_transition_blocked", "Backwards Transition Blocked"),
                    ("state_recovery", "State Recovery"),
                ],
                help_text="Type of activity performed",
                max_length=30,
            ),
        ),
    ]
