# Generated by Django 4.2.11 on 2025-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0006_extend_activity_type_length"),
    ]

    operations = [
        # Only remove the tags field - status_detail already exists
        # Metadata field help text update handled separately
        migrations.AlterField(
            model_name="sessionactivity",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional activity metadata (e.g., old/new values). See ActivityMetadataType in model_types.py",
            ),
        ),
    ]
