# Generated by Django 4.2.11 on 2025-09-08 07:30
# Cleaned up migration: remove tags field and add status_detail field properly

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0007_remove_session_tags"),
    ]

    operations = [
        # Tags field was already removed in migration 0007_remove_session_tags
        # Only add status_detail field which is the main purpose of this migration
        migrations.AddField(
            model_name="searchsession",
            name="status_detail",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
