# Generated by Django 4.2.11 on 2025-09-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0008_add_status_detail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchsession",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="searchsession",
            name="search_sess_owner_i_94ef06_idx",
        ),
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(
                fields=["owner", "-updated_at"], name="search_sess_owner_i_9936d6_idx"
            ),
        ),
    ]
