# Generated by Django 4.2.11 on 2025-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0009_alter_searchsession_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchsession",
            name="status_detail",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Detailed status message for ultra-simple architecture",
                max_length=200,
            ),
        ),
    ]
