# Generated by Django 4.2.11 on 2025-10-02 15:33

from django.db import migrations


def remove_tags_if_exists(apps, schema_editor):
    """
    Safely remove tags column only if it exists.

    This handles the case where the column was already removed
    in migration 0010 in production but still exists in some
    development environments.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if the column exists before trying to drop it
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='search_sessions'
            AND column_name='tags'
        """
        )

        if cursor.fetchone():
            # Column exists, safe to drop
            cursor.execute('ALTER TABLE "search_sessions" DROP COLUMN "tags" CASCADE')
        # If column doesn't exist, do nothing (already removed)


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0010_remove_searchsession_tags_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_tags_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
