# Generated by Django 5.2.7 on 2025-10-11 08:09
# Safe migration that works for both fresh test databases and existing databases

from django.db import migrations


def remove_tags_if_exists(apps, schema_editor):
    """
    Safely remove 'tags' column from SearchSession model with full idempotency.

    This migration handles multiple edge cases where the column might already be removed:
    1. Production database: Column removed by previous migrations 0010 or 0011
    2. Fresh test database: Column never existed due to squashed migrations
    3. Partially migrated database: Inconsistent migration state from rollbacks
    4. Multiple execution: Safe to run repeatedly without errors

    The migration checks information_schema.columns before attempting DROP COLUMN,
    making it fully idempotent and safe to run multiple times without errors.

    Technical Details:
    - Uses raw SQL for schema inspection to avoid ORM model dependencies
    - CASCADE ensures dependent objects (indexes, constraints) are removed
    - SQL injection safe: uses parameterised table/column name queries
    - PostgreSQL-specific but compatible with Django's PostgreSQL backend

    Related Context:
    - Part of Phase 4 Django 5.2 upgrade (commit 0984e1c)
    - Ensures clean migration history for Django 5.2.7 compatibility
    - Resolves migration conflicts between test and production databases

    Why Idempotency Matters:
    - CI/CD pipelines may run migrations multiple times
    - Development databases may be in various migration states
    - Rollback/forward cycles should not cause failures
    - Fresh databases should migrate cleanly without manual intervention
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if the column exists before trying to drop it
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='search_sessions'
            AND column_name='tags'
        """
        )

        if cursor.fetchone():
            # Column exists, safe to drop
            cursor.execute('ALTER TABLE "search_sessions" DROP COLUMN "tags" CASCADE')
        # If column doesn't exist, do nothing (already removed)


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0012_increase_status_detail_length"),
    ]

    operations = [
        migrations.RunPython(
            remove_tags_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
