# Generated by Django 5.1.13 on 2025-10-19 18:32
# Modified to be idempotent - safe to run even if organisation_id column exists

from django.conf import settings
from django.db import migrations


def add_organisation_field_if_not_exists(apps, schema_editor):
    """
    Safely add organisation_id field if it doesn't already exist.

    This handles the case where the field was already added in a previous
    migration attempt or exists in the current database schema.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if organisation_id column exists
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='search_sessions'
            AND column_name='organisation_id'
            """
        )

        if not cursor.fetchone():
            # Column doesn't exist, safe to add it
            cursor.execute("""
                ALTER TABLE "search_sessions"
                ADD COLUMN "organisation_id" uuid NULL
            """)

            # Add foreign key constraint
            cursor.execute("""
                ALTER TABLE "search_sessions"
                ADD CONSTRAINT "search_sessions_organisation_id_b268089a_fk_organisations_id"
                FOREIGN KEY ("organisation_id")
                REFERENCES "organisations"("id")
                DEFERRABLE INITIALLY DEFERRED
            """)

            # Add index
            cursor.execute("""
                CREATE INDEX "search_sess_organis_487e1d_idx"
                ON "search_sessions" ("organisation_id", "status")
            """)
        # If column exists, do nothing (already added)


def create_default_organisation_and_link_sessions(apps, schema_editor):
    """
    Data migration to link existing SearchSessions to default organisation.

    STRATEGY:
    1. Create "Default Organisation" if none exists
    2. Link all existing sessions to default org
    3. Assign all existing users to default org as Lead Reviewers

    This preserves existing access patterns while enabling multi-tenancy.

    Uses raw SQL because the organisation_id field was added via raw SQL,
    so Django's migration state doesn't know about it yet.
    """
    from django.db import connection

    Organisation = apps.get_model("organisation", "Organisation")
    OrganisationMembership = apps.get_model("organisation", "OrganisationMembership")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    # Create default organisation using ORM (this works fine)
    default_org, created = Organisation.objects.get_or_create(
        slug="default",
        defaults={
            "name": "Default Organisation",
            "default_min_reviewers": 1,  # Existing behaviour (single screening)
            "require_dual_review": False,
            "default_conflict_resolution_method": "DESIGNATED_ARBITRATOR",
        },
    )

    if created:
        print(f"Created default organisation: {default_org.name}")

    # Link all existing sessions to default org using raw SQL
    # (Can't use ORM because migration state doesn't know about organisation field)
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE search_sessions
            SET organisation_id = %s
            WHERE organisation_id IS NULL
            """,
            [default_org.id],
        )
        sessions_updated = cursor.rowcount
        print(f"Linked {sessions_updated} existing sessions to default organisation")

    # Create memberships for all users using ORM (works fine)
    existing_users = User.objects.all()
    memberships_created = 0
    for user in existing_users:
        _, created = OrganisationMembership.objects.get_or_create(
            user=user,
            organisation=default_org,
            defaults={
                "role": "LEAD_REVIEWER",  # Preserve existing access
                "can_create_reviews": True,
            },
        )
        if created:
            memberships_created += 1

    print(f"Created {memberships_created} new memberships for existing users")


def reverse_migration(apps, schema_editor):
    """
    Rollback: Remove organisation links.

    STRATEGY: Set SearchSession.organisation to null
    WARNING: Does NOT delete Organisation (preserve data)

    Uses raw SQL for same reason as forward migration.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE search_sessions
            SET organisation_id = NULL
            """
        )
        sessions_updated = cursor.rowcount
        print(f"Removed organisation link from {sessions_updated} sessions")


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0001_initial"),
        ("review_manager", "0013_remove_searchsession_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use RunPython to conditionally add the field (idempotent)
        migrations.RunPython(
            add_organisation_field_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        # Data migration to create default org and link sessions
        migrations.RunPython(
            create_default_organisation_and_link_sessions, reverse_migration
        ),
    ]
