# Generated by Django 5.1.13 on 2025-10-20 14:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0002_organisation_default_assignment_strategy_and_more"),
        ("review_manager", "0014_add_organisation_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Session Created"),
                    ("status_changed", "Status Changed"),
                    ("search_defined", "Search Defined"),
                    ("search_executed", "Search Executed"),
                    ("results_processed", "Results Processed"),
                    ("review_started", "Review Started"),
                    ("review_completed", "Review Completed"),
                    ("exported", "Data Exported"),
                    ("shared", "Session Shared"),
                    ("note_added", "Note Added"),
                    ("settings_changed", "Settings Changed"),
                    ("auto_execution", "Automatic Execution"),
                    ("execution_started", "Execution Started"),
                    ("execution_failed", "Execution Failed"),
                    ("processing_failed", "Processing Failed"),
                    ("transition_failed", "Transition Failed"),
                    ("manual_recovery", "Manual Recovery"),
                    ("auto_recovery", "Automatic Recovery"),
                    ("api_recovery", "API Recovery"),
                    ("recovery_action", "Recovery Action"),
                    ("search_started", "Search Started"),
                    ("state_change", "State Change"),
                    ("state_transition", "State Transition"),
                    ("status_change", "Status Change"),
                    ("state_reconciliation", "State Reconciliation"),
                    ("backwards_transition_blocked", "Backwards Transition Blocked"),
                    ("state_recovery", "State Recovery"),
                    ("configuration_saved", "Configuration Saved"),
                    ("configuration_changed", "Configuration Changed"),
                ],
                help_text="Type of activity performed",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ReviewConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Configuration version number (increments on changes)",
                    ),
                ),
                (
                    "review_mode",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Reviewer"),
                            ("DUAL", "Dual Reviewer"),
                            ("TRIPLE", "Triple Reviewer"),
                            ("MULTIPLE", "Multiple Reviewer"),
                        ],
                        default="DUAL",
                        help_text="Number of independent reviewers required per result",
                        max_length=20,
                    ),
                ),
                (
                    "min_reviewers_per_result",
                    models.IntegerField(
                        default=2,
                        help_text="Minimum reviewers required (auto-set by review_mode)",
                    ),
                ),
                (
                    "assignment_strategy",
                    models.CharField(
                        choices=[
                            ("FIRST_COME", "First-Come-First-Served"),
                            ("MANUAL", "Manual Assignment by Lead"),
                        ],
                        default="FIRST_COME",
                        help_text="How results are assigned to reviewers",
                        max_length=30,
                    ),
                ),
                (
                    "conflict_resolution_method",
                    models.CharField(
                        choices=[
                            ("DESIGNATED_ARBITRATOR", "Designated Arbitrator"),
                            ("LEAD_ARBITRATION", "Lead Reviewer Arbitrates"),
                            ("CONSENSUS", "Consensus Discussion"),
                            ("MAJORITY_VOTE", "Majority Vote"),
                        ],
                        default="DESIGNATED_ARBITRATOR",
                        help_text="How conflicts between reviewers are resolved",
                        max_length=30,
                    ),
                ),
                (
                    "blind_screening_enforced",
                    models.BooleanField(
                        default=True,
                        help_text="Whether reviewers can see others' decisions (always True for PRISMA compliance)",
                    ),
                ),
                (
                    "designated_arbitrator_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of designated arbitrator",
                        max_length=254,
                    ),
                ),
                (
                    "designated_arbitrator_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of designated arbitrator",
                        max_length=255,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this configuration version became active",
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this configuration version was superseded (null = current)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this configuration",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designated_arbitrator_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account of arbitrator (if registered)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arbitrated_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="Organisation managing this review configuration",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_configurations",
                        to="organisation.organisation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Search session this configuration applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="review_manager.searchsession",
                    ),
                ),
            ],
            options={
                "db_table": "review_configurations",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        help_text="Justification for configuration change"
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        default=dict,
                        help_text="Fields changed: {'field_name': {'old': X, 'new': Y}}",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When configuration was changed"
                    ),
                ),
                (
                    "results_affected_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of results already reviewed under old configuration",
                    ),
                ),
                (
                    "deviation_tag_applied",
                    models.BooleanField(
                        default=False,
                        help_text="Whether affected results were tagged as configuration deviations",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who made the configuration change",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session that was reconfigured",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_changes",
                        to="review_manager.searchsession",
                    ),
                ),
                (
                    "from_configuration",
                    models.ForeignKey(
                        help_text="Previous configuration version",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes_from",
                        to="review_manager.reviewconfiguration",
                    ),
                ),
                (
                    "to_configuration",
                    models.ForeignKey(
                        help_text="New configuration version",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes_to",
                        to="review_manager.reviewconfiguration",
                    ),
                ),
            ],
            options={
                "db_table": "configuration_changes",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="searchsession",
            name="current_configuration",
            field=models.ForeignKey(
                blank=True,
                help_text="Current active configuration for this review session",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_sessions",
                to="review_manager.reviewconfiguration",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewconfiguration",
            index=models.Index(
                fields=["session", "version"], name="review_conf_session_43383f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewconfiguration",
            index=models.Index(
                fields=["session", "effective_from"],
                name="review_conf_session_e4f5b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewconfiguration",
            index=models.Index(
                fields=["organisation"], name="review_conf_organis_6828d7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewconfiguration",
            constraint=models.UniqueConstraint(
                fields=("session", "version"),
                name="unique_session_configuration_version",
            ),
        ),
        migrations.AddIndex(
            model_name="configurationchange",
            index=models.Index(
                fields=["session", "-changed_at"], name="configurati_session_ddc638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configurationchange",
            index=models.Index(
                fields=["changed_by"], name="configurati_changed_70e4df_idx"
            ),
        ),
    ]
