# Generated by Django 5.1.13 on 2025-10-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0002_organisation_default_assignment_strategy_and_more"),
        ("review_manager", "0016_alter_sessionactivity_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewconfiguration",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text="Organisation managing this review configuration (optional for personal reviews)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_configurations",
                to="organisation.organisation",
            ),
        ),
    ]
