# Generated by Django 5.1.13 on 2025-10-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0017_make_organisation_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewconfiguration",
            name="assignment_strategy",
        ),
        migrations.RemoveField(
            model_name="reviewconfiguration",
            name="review_mode",
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="consensus_criteria",
            field=models.CharField(
                choices=[
                    ("MAJORITY", "Simple Majority (>50%)"),
                    ("UNANIMOUS", "Unanimous Agreement (100%)"),
                ],
                default="MAJORITY",
                help_text="What defines agreement when reviewers vote",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewconfiguration",
            name="conflict_resolution_method",
            field=models.CharField(
                choices=[
                    ("DESIGNATED_ARBITRATOR", "Designated Arbitrator"),
                    ("LEAD_ARBITRATION", "Lead Reviewer Arbitrates"),
                    ("CONSENSUS", "Consensus Discussion"),
                ],
                default="DESIGNATED_ARBITRATOR",
                help_text="How conflicts between reviewers are resolved",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="reviewconfiguration",
            name="min_reviewers_per_result",
            field=models.IntegerField(
                choices=[
                    (1, "1 Reviewer (Single Screening)"),
                    (2, "2 Reviewers (Dual Screening)"),
                    (3, "3 Reviewers (Triple Screening)"),
                    (4, "4 Reviewers (Multiple Screening)"),
                ],
                default=2,
                help_text="Number of independent reviewers required per result",
            ),
        ),
    ]
