# Generated by Django 5.1.13 on 2025-10-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0018_simplify_review_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewconfiguration",
            name="invited_reviewers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of reviewers invited to participate (stores email, first_name, last_name)",
            ),
        ),
        migrations.AlterField(
            model_name="reviewconfiguration",
            name="conflict_resolution_method",
            field=models.CharField(
                choices=[
                    ("LEAD_ARBITRATION", "Lead Reviewer Arbitrates"),
                    ("DESIGNATED_ARBITRATOR", "Designated Arbitrator"),
                    ("CONSENSUS", "Consensus Discussion"),
                ],
                default="LEAD_ARBITRATION",
                help_text="How conflicts between reviewers are resolved",
                max_length=30,
            ),
        ),
    ]
