# Generated by Django 5.1.13 on 2025-10-21 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0019_add_invited_reviewers_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invitee_email",
                    models.EmailField(
                        help_text="Email address of invitee", max_length=254
                    ),
                ),
                (
                    "invitee_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional display name of invitee",
                        max_length=255,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Magic link token for invitation acceptance",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        help_text="Current status of the invitation",
                        max_length=20,
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the invitation was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the invitation expires"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted/declined",
                        null=True,
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who accepted the invitation (null until accepted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Review session being shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_invitations",
                        to="review_manager.searchsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Invitation",
                "verbose_name_plural": "Review Invitations",
                "db_table": "review_invitations",
                "ordering": ["-invited_at"],
                "indexes": [
                    models.Index(
                        fields=["invitee_email", "status"],
                        name="review_invi_invitee_ebba87_idx",
                    ),
                    models.Index(fields=["token"], name="review_invi_token_aa30c3_idx"),
                    models.Index(
                        fields=["session", "status"],
                        name="review_invi_session_2cef8e_idx",
                    ),
                ],
                "unique_together": {("session", "invitee_email")},
            },
        ),
    ]
