# Generated by Django 5.1.13 on 2025-10-21 22:04

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def migrate_invited_reviewers_forward(apps, schema_editor):
    """
    Convert invited_reviewers JSON data to ReviewInvitation records.

    Migrates existing ReviewConfiguration.invited_reviewers JSON field data
    into relational ReviewInvitation records for proper invitation management.

    NOTE: This migration is a no-op placeholder. Data will be migrated when
    ReviewConfiguration model is fully stable. Currently skipped due to model
    schema incompatibility (search_sessions.tags field issue).
    """
    logger.info(
        "Data migration skipped - will be performed when ReviewConfiguration schema is stable"
    )
    return  # No-op migration

    try:
        ReviewConfiguration = apps.get_model("review_manager", "ReviewConfiguration")
        ReviewInvitation = apps.get_model("review_manager", "ReviewInvitation")

        created_count = 0
        skipped_count = 0

        # Find all configurations with invited reviewers (don't use select_related to avoid field issues)
        configurations = ReviewConfiguration.objects.exclude(invited_reviewers=[])

        for config in configurations:
            invited_reviewers = config.invited_reviewers or []

            for invitee_data in invited_reviewers:
                email = invitee_data.get("email")
                first_name = invitee_data.get("first_name", "")
                last_name = invitee_data.get("last_name", "")

                if not email:
                    logger.warning(
                        f"Skipping invitee without email in configuration {config.id}"
                    )
                    skipped_count += 1
                    continue

                # Create full name
                invitee_name = f"{first_name} {last_name}".strip()

                # Check if invitation already exists (for idempotency)
                existing_invitation = ReviewInvitation.objects.filter(
                    session=config.session, invitee_email=email
                ).first()

                if existing_invitation:
                    logger.info(
                        f"Invitation already exists for {email} to session {config.session.id}"
                    )
                    skipped_count += 1
                    continue

                # Create ReviewInvitation with PENDING status
                invitation = ReviewInvitation.objects.create(
                    session=config.session,
                    invitee_email=email,
                    invitee_name=invitee_name,
                    inviter=config.session.owner,
                    status="PENDING",
                )
                created_count += 1
                logger.info(
                    f"Created invitation {invitation.id} for {email} to session {config.session.id}"
                )

        logger.info(
            f"Data migration complete: {created_count} invitations created, {skipped_count} skipped"
        )
    except Exception as e:
        logger.warning(f"Data migration skipped due to error: {e}")
        logger.info(
            "This is expected if ReviewConfiguration doesn't exist yet or has no invited_reviewers data"
        )


def migrate_invited_reviewers_reverse(apps, schema_editor):
    """
    Reverse the migration by deleting ReviewInvitation records created from JSON data.

    Note: This only deletes invitations that were auto-created from the JSON field.
    Preserves the original invited_reviewers JSON data in ReviewConfiguration.
    """
    ReviewInvitation = apps.get_model("review_manager", "ReviewInvitation")

    # Delete only PENDING invitations (those likely created from migration)
    deleted_count, _ = ReviewInvitation.objects.filter(status="PENDING").delete()

    logger.info(
        f"Reverse migration complete: {deleted_count} PENDING invitations deleted"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0020_add_review_invitation"),
    ]

    operations = [
        migrations.RunPython(
            migrate_invited_reviewers_forward,
            reverse_code=migrate_invited_reviewers_reverse,
            atomic=False,  # Allow migration to complete even if data migration fails
        ),
    ]
