# Generated by Django 5.1.13 on 2025-11-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0004_organisation_default_review_mode"),
        ("review_manager", "0022_add_irr_threshold_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewconfiguration",
            name="external_reviewers_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether Information Specialist has approved external reviewers",
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="external_reviewers_approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when external reviewers were approved",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="external_reviewers_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Information Specialist who approved external reviewers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_external_reviewers_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="external_reviewers_pending_approval",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="External reviewers awaiting IS approval. Format: [{email, first_name, last_name}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="external_reviewers_rejected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when external reviewers were rejected",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="external_reviewers_rejected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Information Specialist who rejected external reviewers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_external_reviewers_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="external_reviewers_rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by IS for rejecting external reviewers",
            ),
        ),
        migrations.AlterField(
            model_name="reviewconfiguration",
            name="conflict_resolution_method",
            field=models.CharField(
                choices=[
                    ("CONSENSUS", "Consensus Discussion"),
                    ("LEAD_ARBITRATION", "Lead Reviewer Arbitration"),
                    ("DESIGNATED_ARBITRATOR", "Designated Arbitrator"),
                    ("MAJORITY", "Majority Vote (3+ reviewers)"),
                ],
                default="LEAD_ARBITRATION",
                help_text="How conflicts between reviewers are resolved",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="reviewconfiguration",
            index=models.Index(
                fields=["external_reviewers_approved"], name="idx_ext_rev_approved"
            ),
        ),
    ]
