# Generated by Django 5.1.13 on 2025-11-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0023_add_external_reviewer_approval_fields"),
    ]

    operations = [
        # Note: tags field removal omitted - already removed by migrations 0011, 0013, and 0015
        # Migration 0007 was incomplete (filename suggests removal but operation missing)
        # Subsequent migrations used idempotent raw SQL to safely remove the column
        migrations.AlterField(
            model_name="sessionactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Session Created"),
                    ("status_changed", "Status Changed"),
                    ("search_defined", "Search Defined"),
                    ("search_executed", "Search Executed"),
                    ("results_processed", "Results Processed"),
                    ("review_started", "Review Started"),
                    ("review_completed", "Review Completed"),
                    ("exported", "Data Exported"),
                    ("shared", "Session Shared"),
                    ("note_added", "Note Added"),
                    ("settings_changed", "Settings Changed"),
                    ("auto_execution", "Automatic Execution"),
                    ("execution_started", "Execution Started"),
                    ("execution_failed", "Execution Failed"),
                    ("processing_failed", "Processing Failed"),
                    ("transition_failed", "Transition Failed"),
                    ("manual_recovery", "Manual Recovery"),
                    ("auto_recovery", "Automatic Recovery"),
                    ("api_recovery", "API Recovery"),
                    ("recovery_action", "Recovery Action"),
                    ("search_started", "Search Started"),
                    ("state_change", "State Change"),
                    ("state_transition", "State Transition"),
                    ("status_change", "Status Change"),
                    ("state_reconciliation", "State Reconciliation"),
                    ("backwards_transition_blocked", "Backwards Transition Blocked"),
                    ("state_recovery", "State Recovery"),
                    ("configuration_saved", "Configuration Saved"),
                    ("configuration_changed", "Configuration Changed"),
                    (
                        "external_reviewers_pending_approval",
                        "External Reviewers Pending Approval",
                    ),
                    ("external_reviewers_approved", "External Reviewers Approved"),
                    ("external_reviewers_rejected", "External Reviewers Rejected"),
                ],
                help_text="Type of activity performed",
                max_length=50,
            ),
        ),
    ]
