# Generated by Django 5.1.13 on 2026-02-19 23:45
#
# This migration fixes the Django migration state to match the actual DB schema.
# Migration 0014 added organisation_id via raw SQL (RunPython), so Django's
# migration framework didn't track the schema change. This migration uses
# SeparateDatabaseAndState to update Django's state without modifying the DB
# (which already has the correct schema).
#
# For fresh test DBs, the column is created properly because migration 0014's
# RunPython executes the raw SQL.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0004_organisation_default_review_mode"),
        ("review_manager", "0024_update_activity_type_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove tags field from state only (already removed in earlier migrations)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="searchsession",
                    name="tags",
                ),
            ],
            database_operations=[],
        ),
        # Add organisation field to state only (already exists via 0014 raw SQL)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="searchsession",
                    name="organisation",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Organisation managing this review",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="organisation.organisation",
                    ),
                ),
            ],
            database_operations=[],
        ),
        # Add index to state only (already exists via 0014 raw SQL)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="searchsession",
                    index=models.Index(
                        fields=["organisation", "status"],
                        name="search_sess_organis_487e1d_idx",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
