# Generated by Django 5.1.13 on 2026-02-22 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0025_fix_organisation_field_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewinvitation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reviewinvitation",
            constraint=models.UniqueConstraint(
                fields=("session", "invitee_email"), name="unique_session_invitee_email"
            ),
        ),
    ]
