# Generated by Django 5.1.13 on 2026-02-22 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0026_alter_reviewinvitation_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reviewinvitation",
            name="review_invi_token_aa30c3_idx",
        ),
    ]
