# Generated by Django 5.1.13 on 2026-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0027_remove_redundant_token_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewinvitation",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reviewinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("EXPIRED", "Expired"),
                    ("REVOKED", "Revoked"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                help_text="Current status of the invitation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewinvitation",
            name="token",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
