# Generated by Django 5.1.13 on 2026-02-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0030_backfill_null_org_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewconfiguration",
            name="arbitration_sla_hours",
            field=models.PositiveIntegerField(
                default=48,
                help_text="SLA hours for arbitration/escalation phase (nudge, not enforced)",
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="discussion_sla_hours",
            field=models.PositiveIntegerField(
                default=72,
                help_text="SLA hours for discussion phase (nudge, not enforced)",
            ),
        ),
        migrations.AddField(
            model_name="reviewconfiguration",
            name="revote_sla_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="SLA hours for re-vote phase (nudge, not enforced)",
            ),
        ),
    ]
