# Generated by Django 5.1.13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_manager", "0031_add_sla_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="prisma_other_methods",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User-overridable data for PRISMA 'other methods' column",
            ),
        ),
    ]
