# Generated by Django 4.2.11 on 2025-07-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0003_fix_file_path_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exportreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="exportreport",
            name="export_repo_generat_dcfeaa_idx",
        ),
        migrations.AddIndex(
            model_name="exportreport",
            index=models.Index(
                fields=["generated_by", "-created_at"],
                name="export_repo_generat_1afb68_idx",
            ),
        ),
    ]
