# Generated by Django 4.2.11 on 2025-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0005_remove_unused_export_formats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="export_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("csv", "CSV"), ("json", "JSON")],
                help_text="Export file format",
                max_length=10,
            ),
        ),
    ]
