# Generated by Django 4.2.11 on 2025-08-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0006_alter_exportreport_export_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportreport",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When report was last updated"
            ),
        ),
    ]
