# Generated by Django 4.2.11 on 2025-08-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0007_exportreport_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="parameters",
            field=models.JSONField(
                blank=True, default=dict, help_text="Parameters used to generate report"
            ),
        ),
    ]
