# Generated by Django 4.2.11 on 2025-08-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0009_add_maybe_results_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="file_size_bytes",
            field=models.BigIntegerField(default=0, help_text="File size in bytes"),
        ),
    ]
