# Generated by Django 4.2.11 on 2025-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0010_add_default_file_size_bytes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parameters used to generate report. See ReportParametersType in model_types.py",
            ),
        ),
    ]
