# Generated by Django 4.2.11 on 2025-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0011_alter_exportreport_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="export_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("csv", "CSV"), ("html", "HTML")],
                help_text="Export file format",
                max_length=10,
            ),
        ),
    ]
