# Generated by Django 4.2.11 on 2025-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0012_alter_exportreport_export_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="export_format",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("csv", "CSV"),
                    ("html", "HTML"),
                    ("xlsx", "Excel Spreadsheet"),
                ],
                help_text="Export file format",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exportreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("prisma_flow", "PRISMA Flow Diagram"),
                    ("full_report", "Full PRISMA Report"),
                    ("included_results", "Included Results List"),
                    ("excluded_results", "Excluded Results with Reasons"),
                    ("search_strategy", "Search Strategy Documentation"),
                    ("data_export", "Raw Data Export"),
                    ("offline_backup", "Offline Backup Export"),
                ],
                help_text="Type of report",
                max_length=20,
            ),
        ),
    ]
