# Generated by Django 4.2.11 on 2025-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0013_alter_exportreport_export_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="file_path",
            field=models.FileField(
                help_text="Path to generated file", max_length=255, upload_to="reports/"
            ),
        ),
    ]
