# Generated by Django 5.1.13 on 2025-10-17 13:56

import apps.reporting.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0014_fix_upload_to_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="file_path",
            field=models.FileField(
                help_text="Path to generated file organised by session UUID",
                max_length=255,
                upload_to=apps.reporting.models.report_upload_path,
            ),
        ),
    ]
