# Generated by Django 5.1.13 on 2025-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0015_fix_report_upload_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("prisma_flow", "PRISMA Flow Diagram"),
                    ("full_report", "Full PRISMA Report"),
                    ("included_results", "Included Results List"),
                    ("excluded_results", "Excluded Results with Reasons"),
                    ("search_strategy", "Search Strategy Documentation"),
                    ("data_export", "Raw Data Export"),
                    ("offline_backup", "Offline Backup Export"),
                    ("irr_report", "Inter-Rater Reliability Report"),
                ],
                help_text="Type of report",
                max_length=20,
            ),
        ),
    ]
