# Generated by Django 5.1.13 on 2026-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0016_alter_exportreport_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="exportreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
