# Generated by Django 5.1.13 on 2025-10-19 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organisation display name", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", unique=True),
                ),
                (
                    "default_review_mode",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Reviewer"),
                            ("DUAL", "Dual Independent Reviewers"),
                            ("TRIPLE", "Triple Independent Reviewers"),
                            ("QUAD", "Quad Independent Reviewers"),
                        ],
                        default="DUAL",
                        help_text="Default review mode for new projects",
                        max_length=20,
                    ),
                ),
                (
                    "default_min_reviewers",
                    models.IntegerField(
                        default=2, help_text="Minimum reviewers required per result"
                    ),
                ),
                (
                    "require_dual_review",
                    models.BooleanField(
                        default=False,
                        help_text="Enforce dual review for all projects (org policy)",
                    ),
                ),
                (
                    "max_active_reviews",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum concurrent active reviews (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum organisation members (null = unlimited)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "db_table": "organisations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganisationInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of invitee", max_length=254
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Optional display name", max_length=255
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("INFORMATION_SPECIALIST", "Information Specialist"),
                            ("SENIOR_RESEARCHER", "Senior Researcher"),
                            ("LEAD_REVIEWER", "Lead Reviewer"),
                            ("REVIEWER", "Reviewer"),
                            ("OBSERVER", "Observer"),
                        ],
                        default="REVIEWER",
                        max_length=30,
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organisation.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation Invitation",
                "verbose_name_plural": "Organisation Invitations",
                "db_table": "organisation_invitations",
                "indexes": [
                    models.Index(
                        fields=["email", "status"], name="organisatio_email_f1d912_idx"
                    ),
                    models.Index(fields=["token"], name="organisatio_token_7f6429_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("INFORMATION_SPECIALIST", "Information Specialist"),
                            ("SENIOR_RESEARCHER", "Senior Researcher"),
                            ("LEAD_REVIEWER", "Lead Reviewer"),
                            ("REVIEWER", "Reviewer"),
                            ("OBSERVER", "Observer"),
                        ],
                        help_text="User role within this organisation",
                        max_length=30,
                    ),
                ),
                (
                    "can_create_reviews",
                    models.BooleanField(
                        default=False, help_text="Can create new review projects"
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False,
                        help_text="Can invite/remove organisation members",
                    ),
                ),
                (
                    "can_view_all_reviews",
                    models.BooleanField(
                        default=False, help_text="Can view all reviews in organisation"
                    ),
                ),
                (
                    "can_edit_configurations",
                    models.BooleanField(
                        default=False, help_text="Can modify organisation settings"
                    ),
                ),
                (
                    "can_export_data",
                    models.BooleanField(
                        default=False, help_text="Can export organisation-wide reports"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive members retain historical data but lose access",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organisation.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation Membership",
                "verbose_name_plural": "Organisation Memberships",
                "db_table": "organisation_memberships",
                "indexes": [
                    models.Index(
                        fields=["organisation", "is_active"],
                        name="organisatio_organis_44a4d9_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="organisatio_user_id_cfe458_idx",
                    ),
                ],
                "unique_together": {("organisation", "user")},
            },
        ),
    ]
