# Generated by Django 5.1.13 on 2025-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="default_assignment_strategy",
            field=models.CharField(
                choices=[
                    ("FIRST_COME", "First-Come-First-Served"),
                    ("MANUAL", "Manual Assignment by Lead"),
                ],
                default="FIRST_COME",
                help_text="Default assignment strategy for new reviews",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="default_conflict_resolution_method",
            field=models.CharField(
                choices=[
                    ("DESIGNATED_ARBITRATOR", "Designated Arbitrator"),
                    ("LEAD_ARBITRATION", "Lead Reviewer Arbitrates"),
                    ("CONSENSUS", "Consensus Discussion"),
                    ("MAJORITY_VOTE", "Majority Vote"),
                ],
                default="DESIGNATED_ARBITRATOR",
                help_text="Default conflict resolution method for new reviews",
                max_length=30,
            ),
        ),
    ]
