# Generated by Django 5.1.13 on 2025-10-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0002_organisation_default_assignment_strategy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="default_assignment_strategy",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="default_review_mode",
        ),
        migrations.AlterField(
            model_name="organisation",
            name="default_min_reviewers",
            field=models.IntegerField(
                choices=[
                    (1, "1 Reviewer (Single Screening)"),
                    (2, "2 Reviewers (Dual Screening)"),
                    (3, "3 Reviewers (Triple Screening)"),
                    (4, "4 Reviewers (Multiple Screening)"),
                ],
                default=2,
                help_text="Default number of reviewers required per result",
            ),
        ),
    ]
