# Generated by Django 5.1.13 on 2025-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0003_simplify_review_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="default_review_mode",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single Reviewer"),
                    ("DUAL", "Dual Independent Reviewers"),
                    ("TRIPLE", "Triple Independent Reviewers"),
                    ("QUAD", "Quad Independent Reviewers"),
                ],
                default="DUAL",
                help_text="Default review mode for new screening sessions",
                max_length=20,
                verbose_name="Default Review Mode",
            ),
        ),
    ]
