# Generated by Django 5.1.13 on 2026-02-22 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0004_organisation_default_review_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organisationmembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="organisationmembership",
            constraint=models.UniqueConstraint(
                fields=("organisation", "user"), name="unique_organisation_user"
            ),
        ),
    ]
