# Generated by Django 5.1.13 on 2026-02-22 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0005_alter_organisationmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organisationinvitation",
            name="organisatio_token_7f6429_idx",
        ),
    ]
