import { Page } from '@playwright/test';

/**
 * Test User Fixture
 *
 * Unified E2E convention:
 *   - Username prefix: e2e-
 *   - Email domain: @test.local
 *   - Password: TestPass123!
 *   - Login form takes email, authenticates via username internally
 *
 * Management command: create_e2e_users (single source of truth for user definitions)
 */

/** Standard E2E test password -- matches create_e2e_users management command */
export const E2E_PASSWORD = 'TestPass123!';

/** Standard E2E email domain */
export const E2E_EMAIL_DOMAIN = 'test.local';

export interface TestUser {
  username: string;
  email: string;
  password: string;
  firstName?: string;
  lastName?: string;
}

/**
 * Generate a unique test user with timestamp-based identifiers.
 * Uses unified e2e- prefix and @test.local domain.
 */
export function generateTestUser(prefix: string = 'e2e-test'): TestUser {
  const id = Date.now();
  return {
    username: `${prefix}-${id}`,
    email: `${prefix}-${id}@${E2E_EMAIL_DOMAIN}`,
    password: E2E_PASSWORD,
    firstName: prefix.charAt(0).toUpperCase() + prefix.slice(1),
    lastName: 'User',
  };
}

/**
 * Create a test user by filling out the signup form.
 * Signup form has email + password only (username is auto-generated by backend).
 */
export async function createTestUser(
  page: Page,
  user?: Partial<TestUser>
): Promise<TestUser> {
  const testUser: TestUser = {
    username: user?.username ?? `e2e-test-${Date.now()}`,
    email: user?.email ?? `e2e-test-${Date.now()}@${E2E_EMAIL_DOMAIN}`,
    password: user?.password ?? E2E_PASSWORD,
  };

  await page.goto('/accounts/signup/');
  await page.waitForLoadState('domcontentloaded');

  // Fill required fields (email + password only; username auto-generated)
  await page.fill('[data-testid="input-email"], #id_email', testUser.email);
  await page.fill('[data-testid="input-password1"], #id_password1', testUser.password);
  await page.fill('[data-testid="input-password2"], #id_password2', testUser.password);

  // Submit the form
  await page.click('[data-testid="submit-signup-btn"]');

  // Wait for redirect (dashboard or sessions)
  await page.waitForURL(/\/(dashboard|sessions|$)/, { timeout: 10000 }).catch(() => {
    // May fail if user already exists - that's OK for test setup
  });

  return testUser;
}

/**
 * Login as an existing user.
 * Login form takes email, not username.
 */
export async function loginUser(
  page: Page,
  email: string,
  password: string = E2E_PASSWORD
): Promise<void> {
  await page.goto('/accounts/login/');
  await page.waitForSelector('[data-testid="email"]', { state: 'visible' });

  await page.fill('[data-testid="email"]', email);
  await page.fill('[data-testid="password"]', password);
  await page.click('[data-testid="login-btn"]');

  // Wait for redirect to dashboard
  await page.waitForURL(/\/(dashboard|sessions|$)/, { timeout: 15000 });
}

/**
 * Logout the current user
 */
export async function logoutUser(page: Page): Promise<void> {
  await page.goto('/accounts/logout/');
  await page.waitForURL(/\/(accounts\/login\/)?$/, { timeout: 10000 });
}

/**
 * Create and login a test user in one step
 */
export async function createAndLoginTestUser(
  page: Page,
  userOverrides?: Partial<TestUser>
): Promise<TestUser> {
  const user = await createTestUser(page, userOverrides);
  // User should already be logged in after signup
  return user;
}

/**
 * Default test users for E2E tests.
 * Must match apps/accounts/management/commands/create_e2e_users.py exactly.
 */
export const defaultTestUsers = {
  reviewer1: {
    username: 'e2e-reviewer1',
    email: 'e2e-reviewer1@test.local',
    password: E2E_PASSWORD,
  },
  reviewer2: {
    username: 'e2e-reviewer2',
    email: 'e2e-reviewer2@test.local',
    password: E2E_PASSWORD,
  },
  admin: {
    username: 'e2e-admin',
    email: 'e2e-admin@test.local',
    password: E2E_PASSWORD,
  },
  owner: {
    username: 'e2e-owner',
    email: 'e2e-owner@test.local',
    password: E2E_PASSWORD,
  },
};
