"""
Django settings for grey_lit_project project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import sys
from pathlib import Path

from celery.schedules import crontab

from apps.core.env_config import get_env, get_env_bool, get_env_int
from apps.core.logging_config import configure_structlog
from apps.core.utils.secret_key_generator import get_or_generate_secret_key

# Initialize logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# =============================================================================
# SECURITY SETTINGS -- see Django deployment checklist:
# https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# =============================================================================

# SECURITY: SECRET_KEY is used for cryptographic signing (sessions, tokens, CSRF).
# In production, this MUST be a unique, unpredictable, long (>= 32 chars) value
# loaded from the environment. The fallback generator is for first-run convenience
# only -- production.py enforces an explicit key via ImproperlyConfigured.
_raw_secret_key = get_env("SECRET_KEY")
SECRET_KEY = get_or_generate_secret_key(_raw_secret_key, min_length=32)

# SECURITY: DEBUG exposes detailed error pages, stack traces, and settings values.
# MUST be False in production. Environment-specific files override this.
DEBUG = get_env_bool("DEBUG", default=False)

# SECURITY: ALLOWED_HOSTS prevents HTTP Host header attacks. An empty default
# means Django rejects all requests unless overridden by the environment-specific
# settings file (local.py, staging.py, production.py).
ALLOWED_HOSTS: list[str] = []

# Prometheus metrics configuration
PROMETHEUS_METRICS_ENABLED = get_env_bool("PROMETHEUS_METRICS_ENABLED", default=True)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_vite",  # Vite asset management (Issue #27)
    "django.contrib.humanize",  # For template humanize filters
    # Third party apps
    "rest_framework",
    "knox",  # Per-device revocable tokens for extension API
    "drf_spectacular",  # OpenAPI schema generation (Phase 4)
    "cachalot",
    "corsheaders",
    "constance",
    "constance.backends.database",
    # "django_eventstream",  # Replaced with custom SSE implementation (Phase 2)
    # Local apps
    "apps.core",
    "apps.health",
    "apps.accounts",
    "apps.organisation",  # Multi-tenant organisation management
    "apps.review_manager",
    "apps.search_strategy",
    "apps.serp_execution",
    "apps.results_manager",
    "apps.review_results",
    "apps.reporting",
    "apps.feedback",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Correlation ID tracking (replaces RequestIDMiddleware)
    "apps.core.middleware.correlation.CorrelationIDMiddleware",
    # Logging context enrichment
    "apps.core.middleware.logging_context.LoggingContextMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.organisation.middleware.OrganisationMiddleware",  # Organisation context (AFTER Auth)
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_eventstream.middleware.EventStreamMiddleware",  # Replaced with custom SSE
    "apps.core.middleware.performance.PerformanceTrackingMiddleware",  # Performance tracking
]

ROOT_URLCONF = "grey_lit_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.review_manager.context_processors.pending_invitations",
                "apps.core.context_processors.posthog_context",
            ],
        },
    },
]

WSGI_APPLICATION = "grey_lit_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_env("POSTGRES_DB", default="thesis_grey_db"),
        "USER": get_env("POSTGRES_USER", default="thesis_grey_user"),
        "PASSWORD": get_env("POSTGRES_PASSWORD", default="secure_password"),
        "HOST": get_env("DB_HOST", default="db"),
        "PORT": get_env("DB_PORT", default="5432"),
        "ATOMIC_REQUESTS": True,
        "CONN_MAX_AGE": 60,  # Connection pooling
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }
}

# Disable persistent connections during test runs to prevent connection exhaustion.
# With CONN_MAX_AGE=60 and 100 max_connections, large test suites exhaust the pool
# because each test class holds connections open for 60s.
# Also kill idle-in-transaction connections after 30s to prevent stale locks.
if "test" in sys.argv:
    DATABASES["default"]["CONN_MAX_AGE"] = 0
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
    DATABASES["default"]["OPTIONS"]["options"] = (
        "-c idle_in_transaction_session_timeout=30000"
    )
    TEST_RUNNER = "apps.core.test_runner.ConnectionCleanupTestRunner"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Cache Configuration - Default fallback to prevent Redis connection errors
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_table",
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
            "CULL_FREQUENCY": 3,
        },
    }
}

# Note: Redis cache configuration with Prometheus instrumentation is in local.py/production.py

# django-cachalot: automatic ORM query caching
# Requires a compatible cache backend (Redis in local.py/production.py).
# Disabled in test settings to avoid interference with test isolation.
CACHALOT_ENABLED = True
CACHALOT_CACHE = "default"
# Conservative rollout: only cache stable, frequently-read reference tables.
# Expand this set as confidence grows.
CACHALOT_ONLY_CACHABLE_TABLES = frozenset(
    (
        "django_content_type",
        "auth_permission",
        "serp_execution_serproviderconfig",
        "organisation_organisation",
        "organisation_organisationmembership",
        "review_manager_reviewconfiguration",
    )
)

# Celery Base Configuration
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = get_env("STATIC_URL", default="/static/")
STATIC_ROOT = BASE_DIR / "staticfiles"  # Where collectstatic puts files for production

# Static directories - always include the static directory path
# This ensures collectstatic can find our custom static files
STATICFILES_DIRS = [BASE_DIR / "static"]

# Vite Configuration (Issue #27 & #29: Dynamic asset resolution)
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static" / "dist"
DJANGO_VITE_MANIFEST_PATH = DJANGO_VITE_ASSETS_PATH / ".vite" / "manifest.json"
DJANGO_VITE_STATIC_URL_PREFIX = (
    "dist"  # Issue #29: Assets are in /static/dist/ subdirectory
)

# Development mode (HMR support - future enhancement)
DJANGO_VITE_DEV_MODE = DEBUG and get_env_bool("VITE_DEV_MODE", default=False)
DJANGO_VITE_DEV_SERVER_HOST = get_env("VITE_DEV_SERVER_HOST", default="localhost")
DJANGO_VITE_DEV_SERVER_PORT = get_env_int("VITE_DEV_SERVER_PORT", default=5173)

# Media files
MEDIA_URL = get_env("MEDIA_URL", default="/media/")
MEDIA_ROOT = BASE_DIR / "media"

# File upload limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB (covers audio + screenshot)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB per file

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Default backend
    "apps.accounts.backends.RoleBasedPermissionBackend",  # Organisation-based permissions
]

# Authentication Settings
LOGIN_URL = "accounts:login"
# LOGIN_REDIRECT_URL is now handled by custom LoginView in accounts app
# LOGIN_REDIRECT_URL = "accounts:profile"
LOGOUT_REDIRECT_URL = "accounts:login"

# =============================================================================
# SESSION SECURITY
# =============================================================================
# Use cached_db to avoid SynchronousOnlyOperation under ASGI (Uvicorn workers).
# Reads from cache (Redis), writes to both cache + DB. Falls back to DB if cache unavailable.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = (
    False  # Disabled for memory/DB savings (was True for Issue #33 CSRF)
)
# SECURITY: HttpOnly prevents JavaScript access to the session cookie, mitigating
# XSS-based session theft. This should always be True.
SESSION_COOKIE_HTTPONLY = True
# SECURITY: Secure and SameSite defaults. Environment-specific files override
# these for production (Secure=True) or local dev (Secure=False for HTTP).
SESSION_COOKIE_SECURE = False  # Overridden to True in production.py
SESSION_COOKIE_SAMESITE = "Lax"  # Prevents CSRF via cross-origin GET requests

# =============================================================================
# CSRF PROTECTION
# =============================================================================
# SECURITY: CSRF cookie settings. HttpOnly=False because the Vue SPA reads the
# CSRF token from the cookie to include in X-CSRFToken headers for AJAX requests.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False  # Overridden to True in production.py
CSRF_COOKIE_SAMESITE = "Lax"  # Prevents cross-origin CSRF via GET

# =============================================================================
# SECURITY HEADERS (base defaults -- production.py adds HSTS and stricter values)
# =============================================================================
# SECURITY: Prevents the page from being rendered in a frame, mitigating clickjacking.
X_FRAME_OPTIONS = "DENY"
# SECURITY: Stops browsers from MIME-sniffing the content-type, preventing
# attackers from disguising executable content as a benign type.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Celery Configuration
CELERY_BROKER_URL = get_env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = get_env("CELERY_RESULT_BACKEND", default="redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


# Session Monitor Configuration
# Use environment variable for flexibility in different environments
USE_NEW_SESSION_MONITOR = get_env_bool(
    "USE_NEW_SESSION_MONITOR", default=False
)  # Start with False for safety
# Consider using Git hash or timestamp for cache busting
STATIC_VERSION = get_env("STATIC_VERSION", default="1.0.0")

# SSE Configuration for real-time updates
SSE_KEEP_ALIVE_INTERVAL = 30  # seconds
SSE_RECONNECT_TIMEOUT = 5  # seconds

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    # === ADAPTIVE MONITORING (PRP: Activity-Based Monitoring) ===
    "adaptive-session-monitor": {
        "task": "apps.core.tasks.adaptive_session_monitor",
        "schedule": 300.0,  # Every 5 minutes - adaptive intervals inside task (optimised from 2min)
        "options": {
            "queue": "monitoring",
            "priority": 3,  # Lowered from 8 to prioritise user-initiated tasks
        },
    },
    # === CONSOLIDATED MAINTENANCE ===
    "consolidated-maintenance": {
        "task": "apps.core.tasks.consolidated_maintenance",
        "schedule": crontab(minute="*/15"),  # Every 15 minutes
        "options": {
            "queue": "monitoring",
            "expires": 60 * 12,
        },
    },
    # === MONITORING STATISTICS ===
    "monitoring-statistics": {
        "task": "apps.core.tasks.monitoring_statistics",
        "schedule": crontab(minute="*/30"),  # Every 30 minutes
        "options": {
            "queue": "monitoring",
            "expires": 60 * 25,
        },
    },
    # === ESSENTIAL DAILY/HOURLY TASKS ===
    "update-session-statistics": {
        "task": "apps.review_manager.tasks.maintenance.update_session_statistics",
        "schedule": crontab(minute="*/30"),  # Every 30 minutes
        "options": {
            "queue": "monitoring",
        },
    },
    "cleanup-old-sessions": {
        "task": "apps.review_manager.tasks.maintenance.cleanup_old_sessions",
        "schedule": crontab(hour=3, minute=0),  # Daily at 3 AM
        "kwargs": {"days_old": 365},
        "options": {
            "queue": "monitoring",
        },
    },
    "comprehensive-recovery": {
        "task": "apps.review_manager.tasks.maintenance.comprehensive_recovery",
        "schedule": crontab(hour=2, minute=0),  # Daily at 2 AM (was hourly)
        "options": {
            "queue": "monitoring",
            "expires": 60 * 120,  # 2 hours
        },
    },
    "warm-active-caches": {
        "task": "apps.review_manager.tasks.cache.warm_active_session_caches",
        "schedule": crontab(minute="*/15"),  # Every 15 minutes (optimised from 10min)
        "options": {
            "queue": "monitoring",
            "expires": 60 * 14,
            "priority": 3,  # Low priority - don't block user tasks
        },
    },
    "cleanup-orphaned-processing": {
        "task": "apps.results_manager.tasks.monitoring.cleanup_orphaned_processing_sessions",
        "schedule": crontab(hour=2, minute=30),  # Daily at 2:30 AM
        "options": {
            "queue": "monitoring",
        },
    },
    # === CONFLICT SLA REMINDERS ===
    "check-conflict-sla-reminders": {
        "task": "apps.review_results.tasks.check_conflict_sla_reminders",
        "schedule": crontab(minute=0),  # Every hour, on the hour
        "options": {"queue": "monitoring"},
    },
}

# Celery Task Routing - dedicated queue for monitoring
CELERY_TASK_ROUTES = {
    "apps.core.tasks.adaptive_session_monitor": {"queue": "monitoring"},
    "apps.core.tasks.consolidated_maintenance": {"queue": "monitoring"},
    "apps.core.tasks.monitoring_statistics": {"queue": "monitoring"},
    # Add other task routes as needed
}

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "knox.auth.TokenAuthentication",  # Extension API (per-device tokens)
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",  # OpenAPI schema (Phase 4)
}

# DRF Spectacular Settings (OpenAPI Documentation)
SPECTACULAR_SETTINGS = {
    "TITLE": "Agent Grey Dual-Screening API",
    "DESCRIPTION": "RESTful APIs for dual-reviewer systematic literature screening",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
}

# =============================================================================
# CORS CONFIGURATION (Phase 3: Consensus Discussion Vue 3 SPA)
# =============================================================================
# SECURITY: CORS_ALLOWED_ORIGINS is intentionally empty here. Each environment
# file populates it (production.py reads from env var, local.py allows all).
CORS_ALLOWED_ORIGINS: list[str] = []
# SECURITY: CORS_ALLOW_CREDENTIALS=True sends cookies cross-origin. This is
# required for session-based auth with the Vue SPA but means CORS_ALLOWED_ORIGINS
# must never be "*" -- Django-CORS enforces this automatically.
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
# Allow Chrome/Edge extension origins on the extension API paths only.
# Production: set ALLOWED_EXTENSION_IDS to a comma-separated list of extension ids.
_extension_ids = [
    eid.strip()
    for eid in get_env("ALLOWED_EXTENSION_IDS", default="").split(",")
    if eid.strip()
]
if _extension_ids:
    CORS_ALLOWED_ORIGIN_REGEXES = []
    CORS_ALLOWED_ORIGINS = list(globals().get("CORS_ALLOWED_ORIGINS", [])) + [
        f"chrome-extension://{eid}" for eid in _extension_ids
    ]
elif DEBUG:
    # Local dev convenience only: accept any extension id while DEBUG is on.
    CORS_ALLOWED_ORIGIN_REGEXES = [r"^chrome-extension://[a-z]{32}$"]
else:
    # No extension ids configured in a non-debug environment: allow none.
    CORS_ALLOWED_ORIGIN_REGEXES = []

# Scope extension CORS to /api/extension/ only.
CORS_URLS_REGEX = r"^/api/extension/.*$"

# =============================================================================
# KNOX TOKEN CONFIGURATION (browser-extension API authentication)
# =============================================================================
from datetime import timedelta  # noqa: E402

KNOX_TOKEN_MODEL = "knox.AuthToken"
REST_KNOX = {
    "TOKEN_TTL": timedelta(days=365),  # Long-lived; user-revocable
    "AUTO_REFRESH": False,
    "MIN_REFRESH_INTERVAL": 60,
    "TOKEN_LIMIT_PER_USER": 10,  # Max devices per account
    "TOKEN_PREFIX": "ag_ext_",  # Visual distinction from session tokens
}

# SERP Execution Configuration
SERPER_API_KEY = get_env("SERPER_API_KEY", default="")
SERPER_DAILY_BUDGET = get_env("SERPER_DAILY_BUDGET", default="10.00", cast=float)
SERPER_MONTHLY_BUDGET = get_env("SERPER_MONTHLY_BUDGET", default="300.00", cast=float)
SERP_CACHE_ENABLED = get_env_bool("SERP_CACHE_ENABLED", default=True)
SERP_CACHE_TTL = get_env_int("SERP_CACHE_TTL", default=86400)  # 24 hours

# Enable Serper API mocking for development/testing (when API key is placeholder)
ENABLE_SERPER_MOCKING = get_env_bool("ENABLE_SERPER_MOCKING", default=False)

# Groq API (Whisper transcription for voice feedback)
GROQ_API_KEY = get_env("GROQ_API_KEY", default="")

# Rate Limiting Configuration for Serper API
# Configures client-side throttling to prevent API quota exhaustion
SERPER_RATE_LIMIT = get_env_int(
    "SERPER_RATE_LIMIT", default=50
)  # requests per minute (allows 6 queries × 10 pages with headroom)
SERPER_RATE_BURST = get_env_int(
    "SERPER_RATE_BURST", default=60
)  # burst capacity (allow bursting for parallel queries)
SERPER_RATE_PERIOD = get_env_int("SERPER_RATE_PERIOD", default=60)  # 60 seconds

# SearchAPI.io Configuration (Bing provider)
SEARCHAPI_API_KEY = get_env("SEARCHAPI_API_KEY", default="")
SEARCHAPI_BASE_URL = get_env(
    "SEARCHAPI_BASE_URL", default="https://www.searchapi.io/api/v1/search"
)
SEARCHAPI_RATE_LIMIT = get_env_int("SEARCHAPI_RATE_LIMIT", default=30)

# Logging Configuration
LOG_DIR = BASE_DIR / "logs"
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except FileExistsError:
    # Tolerate a race on bind-mounted dev volumes (Windows/WSL): a concurrent
    # process (e.g. the autoreloader) can create the directory between mkdir's
    # internal stat and the syscall, making mkdir(exist_ok=True) re-raise. The
    # directory exists at this point, so there is nothing left to do. An
    # is_dir() re-check is unreliable here due to bind-mount consistency lag.
    pass

# Structured Logging Configuration
# Configure structlog before Django logging
configure_structlog()

# Django logging configuration - integrates with structlog
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(message)s",
        },
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json" if not DEBUG else "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": get_env("APP_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Silence noisy loggers
        "django.utils.autoreload": {
            "level": "WARNING",
        },
        "django.db.backends": {
            "level": "WARNING",  # Set to DEBUG to see SQL queries
        },
    },
}

# Agent Grey Configuration
THESIS_GREY_CONFIG = {
    "search": {
        "default_num_results": 100,
        "default_location": None,  # None means global search
        "default_language": "en",
        "default_file_types": ["pdf"],
    },
    "api": {
        "serper_timeout": 30,
        "rate_limit_per_minute": 100,
        "max_retries": 3,
    },
    "processing": {
        "batch_size": 50,
        "cache_ttl": 3600,
        "duplicate_threshold": 0.85,
    },
}

# PostHog Product Analytics
POSTHOG_API_KEY: str = get_env("POSTHOG_API_KEY", default="")
POSTHOG_HOST: str = get_env("POSTHOG_HOST", default="https://eu.i.posthog.com")
_posthog_key: str = get_env("POSTHOG_API_KEY", default="")
POSTHOG_ENABLED: bool = get_env_bool("POSTHOG_ENABLED", default=bool(_posthog_key))

# TestMail.app Configuration (for email testing)
TESTMAIL_API_KEY = get_env("TESTMAIL_API_KEY", default="")
TESTMAIL_NAMESPACE = get_env("TESTMAIL_NAMESPACE", default="")

# Django Constance Configuration
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_DATABASE_PREFIX = "constance:thesis_grey:"

CONSTANCE_CONFIG = {
    # Search Configuration
    "SEARCH_DEFAULT_NUM_RESULTS": (100, "Default number of search results", int),
    "SEARCH_DEFAULT_LOCATION": ("", "Default search location (empty for global)", str),
    "SEARCH_DEFAULT_LANGUAGE": ("en", "Default search language", str),
    "SEARCH_DEFAULT_FILE_TYPES": ("pdf", "Comma-separated file types", str),
    # API Configuration
    "API_SERPER_TIMEOUT": (30, "Serper API timeout in seconds", int),
    "API_RATE_LIMIT_PER_MINUTE": (100, "API rate limit per minute", int),
    "API_MAX_RETRIES": (3, "Maximum API retry attempts", int),
    # Processing Configuration
    "PROCESSING_BATCH_SIZE": (50, "Batch size for result processing", int),
    "PROCESSING_CACHE_TTL": (3600, "Cache TTL in seconds", int),
    "PROCESSING_DUPLICATE_THRESHOLD": (
        0.85,
        "Similarity threshold for duplicates",
        float,
    ),
    # Issue #100: Result Filtering Transparency Configuration
    "PROCESSING_PRESERVE_FILTERED_RESULTS": (
        True,
        "Store filtered/duplicate results for transparency",
        bool,
    ),
    "PROCESSING_SHOW_ERROR_DETAILS": (
        True,
        "Show detailed error information to users",
        bool,
    ),
    "PROCESSING_STRICTNESS_MODE": (
        "standard",
        "Processing strictness: relaxed|standard|strict",
        str,
    ),
    "RESULT_FILTER_DUPLICATE_HANDLING": (
        "transparent",
        "Duplicate handling: hide|transparent|review",
        str,
    ),
    # Feature Flags
    "FEATURE_ADVANCED_SEARCH": (False, "Enable advanced search features", bool),
    "FEATURE_AI_SUGGESTIONS": (False, "Enable AI-powered suggestions", bool),
    "USE_NEW_SESSION_MONITOR": (False, "Enable new SSE-based session monitor", bool),
    # Monitoring Settings
    "USE_UNIFIED_MONITORING": (
        True,
        "Use unified monitoring task instead of individual tasks",
        bool,
    ),
    "MONITOR_MAX_EXECUTIONS_PER_BATCH": (
        20,
        "Maximum executions to process per monitoring cycle",
        int,
    ),
    "MONITOR_MAX_SESSIONS_PER_BATCH": (
        10,
        "Maximum sessions to process per monitoring cycle",
        int,
    ),
    # Circuit Breaker Settings
    "CB_SERPER_API_FAIL_MAX": (5, "Number of failures before opening circuit", int),
    "CB_SERPER_API_RESET_TIMEOUT": (
        60,
        "Seconds before attempting to close circuit",
        int,
    ),
    "CB_DATABASE_FAIL_MAX": (3, "Database circuit breaker failure threshold", int),
    "CB_DATABASE_RESET_TIMEOUT": (30, "Database circuit breaker reset timeout", int),
    "USE_CIRCUIT_BREAKERS": (True, "Enable circuit breaker protection", bool),
    "CB_NOTIFY_ON_OPEN": (True, "Send notifications when circuit breaker opens", bool),
    "CB_COLLECT_STATISTICS": (True, "Collect circuit breaker statistics", bool),
    # Rate Limiting (Phase 4)
    "API_RATE_LIMIT_BURST": (10, "Burst allowance for rate limiting", int),
    # Invitation & Access Control (Phase C - Security Enhancement)
    "REQUIRE_IS_APPROVAL_FOR_EXTERNAL_INVITES": (
        False,  # Default: False for development/testing
        "Require Information Specialist approval before sending review invitations to external reviewers (reviewers outside the organisation). "
        "When enabled, session owners can propose external reviewers, but invitations will not be sent until an IS approves. "
        "Internal reviewers (organisation members) are always invited immediately regardless of this setting.",
        bool,
    ),
    "INVITATION_RATE_LIMIT_PER_HOUR": (
        10,
        "Maximum number of organisation invitations a user can send per hour (rate limiting)",
        int,
    ),
    "INVITATION_EXPIRY_DAYS": (
        7,
        "Number of days before invitation magic links expire",
        int,
    ),
}

# Organize settings into fieldsets for better admin UI
CONSTANCE_CONFIG_FIELDSETS = {
    "Search Settings": (
        "SEARCH_DEFAULT_NUM_RESULTS",
        "SEARCH_DEFAULT_LOCATION",
        "SEARCH_DEFAULT_LANGUAGE",
        "SEARCH_DEFAULT_FILE_TYPES",
    ),
    "API Settings": (
        "API_SERPER_TIMEOUT",
        "API_RATE_LIMIT_PER_MINUTE",
        "API_MAX_RETRIES",
    ),
    "Processing Settings": (
        "PROCESSING_BATCH_SIZE",
        "PROCESSING_CACHE_TTL",
        "PROCESSING_DUPLICATE_THRESHOLD",
        "PROCESSING_PRESERVE_FILTERED_RESULTS",
        "PROCESSING_SHOW_ERROR_DETAILS",
        "PROCESSING_STRICTNESS_MODE",
        "RESULT_FILTER_DUPLICATE_HANDLING",
    ),
    "Feature Flags": (
        "FEATURE_ADVANCED_SEARCH",
        "FEATURE_AI_SUGGESTIONS",
        "USE_NEW_SESSION_MONITOR",
    ),
    "Monitoring Settings": (
        "USE_UNIFIED_MONITORING",
        "MONITOR_MAX_EXECUTIONS_PER_BATCH",
        "MONITOR_MAX_SESSIONS_PER_BATCH",
    ),
    "Circuit Breaker": (
        "USE_CIRCUIT_BREAKERS",
        "CB_SERPER_API_FAIL_MAX",
        "CB_SERPER_API_RESET_TIMEOUT",
        "CB_DATABASE_FAIL_MAX",
        "CB_DATABASE_RESET_TIMEOUT",
        "CB_NOTIFY_ON_OPEN",
        "CB_COLLECT_STATISTICS",
    ),
    "Rate Limiting": (
        "API_RATE_LIMIT_PER_MINUTE",
        "API_RATE_LIMIT_BURST",
    ),
    "Invitation & Access Control": (
        "REQUIRE_IS_APPROVAL_FOR_EXTERNAL_INVITES",
        "INVITATION_RATE_LIMIT_PER_HOUR",
        "INVITATION_EXPIRY_DAYS",
    ),
}

# Navigation Configuration
NAVIGATION_CONFIG = {
    "SHOW_HEADER_FOR_STAFF": False,  # Hide header for staff users by default
    "ADMIN_GROUPS": ["Administrators"],  # Groups that can access dashboard
    "HIDE_HEADER_URLS": [  # URL names where header should be hidden
        "login",
        "signup",
        "password_reset",
        "password_reset_done",
        "password_reset_confirm",
        "password_reset_complete",
    ],
}

# Performance Monitoring Configuration
PERFORMANCE_MONITORING = {
    "ENABLED": True,
    "TRACK_QUERIES": True,
    "SLOW_QUERY_THRESHOLD": 0.5,  # seconds
    "TRACK_ANONYMOUS": False,  # Don't track anonymous users
}

# Workflow Cache Configuration
WORKFLOW_CACHE_CONFIG = {
    "SESSION_TTL": 300,  # 5 minutes
    "STATS_TTL": 60,  # 1 minute
    "STATIC_TTL": 3600,  # 1 hour
}

# SSE (Server-Sent Events) Configuration
# Using custom SSE implementation instead of django_eventstream
# EVENTSTREAM_STORAGE_CLASS = 'django_eventstream.storage.DjangoModelStorage'
# EVENTSTREAM_ALLOW_ORIGIN = '*'  # Configure properly for production
# EVENTSTREAM_ALLOW_CREDENTIALS = True
# EVENTSTREAM_ALLOW_HEADERS = ['Authorization', 'Content-Type']

# ============================================================================
# PROMETHEUS METRICS (Phase 3)
# ============================================================================

if PROMETHEUS_METRICS_ENABLED:
    # Custom histogram buckets for Agent Grey operations
    PROMETHEUS_LATENCY_BUCKETS = (
        0.01,
        0.05,
        0.1,
        0.25,
        0.5,  # 10ms to 500ms (fast operations)
        1.0,
        2.0,
        5.0,  # 1s to 5s (medium operations)
        10.0,
        30.0,
        60.0,  # 10s to 60s (slow operations)
        float("inf"),
    )
