# Generated by Django 4.2.11 on 2025-08-14 01:29

from django.db import migrations


def create_metadata_schema(apps, schema_editor):
    """
    Create PostgreSQL metadata schema for codebase tracking.
    Skipped on SQLite as it doesn't support schemas or PostgreSQL-specific features.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            -- Create metadata schema
            CREATE SCHEMA IF NOT EXISTS _metadata;

            -- Create metadata storage table
            CREATE TABLE IF NOT EXISTS _metadata.codebase_meta (
                id INTEGER PRIMARY KEY DEFAULT 1,
                data JSONB NOT NULL DEFAULT '{}'::jsonb,
                version INTEGER DEFAULT 1,
                commit_sha VARCHAR(40),
                branch VARCHAR(100),
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT single_row CHECK (id = 1)
            );

            -- Create GIN index for fast JSONB queries
            CREATE INDEX IF NOT EXISTS idx_metadata_data
            ON _metadata.codebase_meta USING GIN(data);

            -- Create update trigger to track modifications
            CREATE OR REPLACE FUNCTION _metadata.update_timestamp()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.updated_at = CURRENT_TIMESTAMP;
                NEW.version = OLD.version + 1;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER update_metadata_timestamp
            BEFORE UPDATE ON _metadata.codebase_meta
            FOR EACH ROW
            EXECUTE FUNCTION _metadata.update_timestamp();

            -- Insert initial empty row
            INSERT INTO _metadata.codebase_meta (data)
            VALUES ('{}'::jsonb)
            ON CONFLICT (id) DO NOTHING;
            """
        )


def drop_metadata_schema(apps, schema_editor):
    """
    Drop metadata schema and all contained objects.
    Skipped on SQLite as the schema was never created.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            -- Drop schema and all objects
            DROP SCHEMA IF EXISTS _metadata CASCADE;
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20250727_0031"),
    ]

    operations = [
        migrations.RunPython(create_metadata_schema, drop_metadata_schema),
    ]
