# Generated by Django 4.2.11 on 2025-08-14 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_metadata_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Creation timestamp",
            ),
            preserve_default=False,
        ),
    ]
