# Generated by fix_uuid_migrations command
# Replaces the problematic raw SQL migration with proper Django operations
# Now with database-specific implementations for PostgreSQL and SQLite

import json
import uuid

from django.db import migrations, models


def populate_uuid_values_postgresql(schema_editor):
    """Populate UUID values for existing Configuration records (PostgreSQL)."""
    # Use raw SQL to populate UUIDs since Django ORM doesn't know about temp_uuid_id yet
    schema_editor.execute(
        """
        UPDATE core_configuration
        SET temp_uuid_id = gen_random_uuid()
        WHERE temp_uuid_id IS NULL;
        """
    )


def migrate_to_uuid_postgresql(apps, schema_editor):
    """
    PostgreSQL-specific UUID primary key migration using Django operations.

    PostgreSQL properly supports:
    - Adding/removing fields
    - Renaming fields
    - Altering primary keys
    """
    # Step 1: Add temporary UUID field
    schema_editor.execute(
        "ALTER TABLE core_configuration ADD COLUMN temp_uuid_id UUID;"
    )

    # Step 2: Populate UUID values
    populate_uuid_values_postgresql(schema_editor)

    # Step 3: Make UUID field non-nullable
    schema_editor.execute(
        "ALTER TABLE core_configuration ALTER COLUMN temp_uuid_id SET NOT NULL;"
    )

    # Step 4: Drop the old id column and its constraints
    schema_editor.execute(
        "ALTER TABLE core_configuration DROP CONSTRAINT core_configuration_pkey CASCADE;"
    )
    schema_editor.execute("ALTER TABLE core_configuration DROP COLUMN id;")

    # Step 5: Rename temp_uuid_id to id
    schema_editor.execute(
        "ALTER TABLE core_configuration RENAME COLUMN temp_uuid_id TO id;"
    )

    # Step 6: Add primary key constraint
    schema_editor.execute("ALTER TABLE core_configuration ADD PRIMARY KEY (id);")


def migrate_to_uuid_sqlite(apps, schema_editor):
    """
    SQLite-specific UUID primary key migration.

    SQLite does not support:
    - Dropping primary key constraints
    - Renaming columns that affect primary keys
    - ALTER TABLE operations that modify constraints

    Solution: Recreate the table with the new schema.
    """
    Configuration = apps.get_model("core", "Configuration")

    # Get existing data
    existing_configs = list(
        Configuration.objects.values(
            "id",
            "key",
            "value",
            "description",
            "created_at",
            "updated_at",
            "updated_by_id",
        )
    )

    # Create new table with UUID primary key
    schema_editor.execute(
        """
        CREATE TABLE core_configuration_new (
            id TEXT PRIMARY KEY NOT NULL,
            key VARCHAR(100) NOT NULL UNIQUE,
            value TEXT NOT NULL,
            description TEXT NOT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            updated_by_id INTEGER NULL,
            FOREIGN KEY (updated_by_id) REFERENCES accounts_user(id) ON DELETE SET NULL
        );
        """
    )

    # Create index on key field
    schema_editor.execute(
        """
        CREATE INDEX core_configuration_key_idx ON core_configuration_new(key);
        """
    )

    # Migrate data with new UUID primary keys
    for config_data in existing_configs:
        new_uuid = str(uuid.uuid4())
        # Serialize value field to JSON string (SQLite doesn't support dict binding)
        value_json = (
            json.dumps(config_data["value"])
            if isinstance(config_data["value"], dict)
            else config_data["value"]
        )

        schema_editor.execute(
            """
            INSERT INTO core_configuration_new
                (id, key, value, description, created_at, updated_at, updated_by_id)
            VALUES (?, ?, ?, ?, ?, ?, ?);
            """,
            [
                new_uuid,
                config_data["key"],
                value_json,
                config_data["description"],
                config_data["created_at"],
                config_data["updated_at"],
                config_data["updated_by_id"],
            ],
        )

    # Drop old table
    schema_editor.execute("DROP TABLE core_configuration;")

    # Rename new table
    schema_editor.execute(
        "ALTER TABLE core_configuration_new RENAME TO core_configuration;"
    )


def migrate_to_uuid(apps, schema_editor):
    """Route to database-specific migration."""
    if schema_editor.connection.vendor == "postgresql":
        migrate_to_uuid_postgresql(apps, schema_editor)
    elif schema_editor.connection.vendor == "sqlite":
        migrate_to_uuid_sqlite(apps, schema_editor)
    else:
        raise NotImplementedError(
            f"UUID migration not implemented for {schema_editor.connection.vendor}"
        )


def reverse_uuid_migration_postgresql(apps, schema_editor):
    """Reverse PostgreSQL UUID migration."""
    # Drop UUID primary key
    schema_editor.execute(
        "ALTER TABLE core_configuration DROP CONSTRAINT core_configuration_pkey CASCADE;"
    )

    # Rename id to temp_uuid_id
    schema_editor.execute(
        "ALTER TABLE core_configuration RENAME COLUMN id TO temp_uuid_id;"
    )

    # Add integer id column with sequence
    schema_editor.execute(
        "ALTER TABLE core_configuration ADD COLUMN id SERIAL PRIMARY KEY;"
    )

    # Drop temp UUID column
    schema_editor.execute("ALTER TABLE core_configuration DROP COLUMN temp_uuid_id;")


def reverse_uuid_migration_sqlite(apps, schema_editor):
    """
    Reverse SQLite UUID migration.
    Warning: This will lose UUID values and reassign integer IDs.
    """
    Configuration = apps.get_model("core", "Configuration")

    # Get existing data (without IDs)
    existing_configs = list(
        Configuration.objects.values(
            "key", "value", "description", "created_at", "updated_at", "updated_by_id"
        )
    )

    # Recreate table with integer primary key
    schema_editor.execute(
        """
        CREATE TABLE core_configuration_new (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            key VARCHAR(100) NOT NULL UNIQUE,
            value TEXT NOT NULL,
            description TEXT NOT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            updated_by_id INTEGER NULL,
            FOREIGN KEY (updated_by_id) REFERENCES accounts_user(id) ON DELETE SET NULL
        );
        """
    )

    schema_editor.execute(
        """
        CREATE INDEX core_configuration_key_idx ON core_configuration_new(key);
        """
    )

    # Migrate data (new integer IDs will be auto-assigned)
    for config_data in existing_configs:
        # Serialize value field to JSON string (SQLite doesn't support dict binding)
        value_json = (
            json.dumps(config_data["value"])
            if isinstance(config_data["value"], dict)
            else config_data["value"]
        )

        schema_editor.execute(
            """
            INSERT INTO core_configuration_new
                (key, value, description, created_at, updated_at, updated_by_id)
            VALUES (?, ?, ?, ?, ?, ?);
            """,
            [
                config_data["key"],
                value_json,
                config_data["description"],
                config_data["created_at"],
                config_data["updated_at"],
                config_data["updated_by_id"],
            ],
        )

    # Drop old table and rename
    schema_editor.execute("DROP TABLE core_configuration;")
    schema_editor.execute(
        "ALTER TABLE core_configuration_new RENAME TO core_configuration;"
    )


def reverse_uuid_migration(apps, schema_editor):
    """Route to database-specific reverse migration."""
    if schema_editor.connection.vendor == "postgresql":
        reverse_uuid_migration_postgresql(apps, schema_editor)
    elif schema_editor.connection.vendor == "sqlite":
        reverse_uuid_migration_sqlite(apps, schema_editor)
    else:
        raise NotImplementedError(
            f"UUID reverse migration not implemented for {schema_editor.connection.vendor}"
        )


class Migration(migrations.Migration):
    """
    Proper UUID primary key migration using database-aware operations.

    This migration converts the Configuration model's primary key from BigAutoField
    to UUIDField. It handles PostgreSQL and SQLite differently due to their
    different ALTER TABLE capabilities.

    PostgreSQL: Uses ALTER TABLE operations to modify the existing table.
    SQLite: Recreates the table with the new schema (SQLite limitation).
    """

    dependencies = [
        ("core", "0004_configuration_created_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations (actual SQL changes)
            database_operations=[
                migrations.RunPython(migrate_to_uuid, reverse_uuid_migration),
            ],
            # State operations (Django's understanding of the schema)
            state_operations=[
                # Add temporary UUID field
                migrations.AddField(
                    model_name="configuration",
                    name="temp_uuid_id",
                    field=models.UUIDField(default=uuid.uuid4, null=True),
                ),
                # Remove old integer id
                migrations.RemoveField(
                    model_name="configuration",
                    name="id",
                ),
                # Rename temp_uuid_id to id
                migrations.RenameField(
                    model_name="configuration",
                    old_name="temp_uuid_id",
                    new_name="id",
                ),
                # Make id field a proper UUID primary key
                migrations.AlterField(
                    model_name="configuration",
                    name="id",
                    field=models.UUIDField(
                        primary_key=True, default=uuid.uuid4, editable=False
                    ),
                ),
                # Update value field
                migrations.AlterField(
                    model_name="configuration",
                    name="value",
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration value (JSON format)",
                    ),
                ),
            ],
        ),
    ]
