# Generated by Django 4.2.11 on 2025-08-14 16:18
# Converted to no-op migration since 0005 now handles UUID conversion properly


from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration - UUID conversion already handled by migration 0005.

    This migration was originally generated to alter the id field to UUID,
    but migration 0005 was later updated to handle the full UUID conversion
    including both database changes and Django state updates. This migration
    is kept for historical migration chain integrity but performs no operations.
    """

    dependencies = [
        ("core", "0005_configuration_uuid_proper"),
    ]

    operations = [
        # No operations needed - migration 0005 handles everything
    ]
