# Generated by Django 4.2.11 on 2025-08-26 12:40

from django.db import migrations


def initialize_session_monitor_flag(apps, schema_editor):
    """Initialize the USE_NEW_SESSION_MONITOR feature flag in Constance."""
    from constance.backends.database import DatabaseBackend

    # Initialize the feature flag to True (enable new SSE monitor)
    backend = DatabaseBackend()
    backend.set("USE_NEW_SESSION_MONITOR", True)


def reverse_session_monitor_flag(apps, schema_editor):
    """Remove the USE_NEW_SESSION_MONITOR feature flag."""
    from constance.backends.database import DatabaseBackend

    _backend = DatabaseBackend()
    try:
        # Delete the key if it exists
        from constance.models import Constance

        Constance.objects.filter(key="USE_NEW_SESSION_MONITOR").delete()
    except Exception:
        pass  # Ignore if doesn't exist or other database errors


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_configuration_id_alter_configuration_value"),
    ]

    operations = [
        migrations.RunPython(
            initialize_session_monitor_flag, reverse_session_monitor_flag
        ),
    ]
