# Generated by Django 4.2.11 on 2025-09-03 14:55

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_session_monitor_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="value",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Configuration value (JSON format). See ConfigValueType in model_types.py",
            ),
        ),
    ]
