# Generated by Django 5.1.13 on 2025-10-20 21:50
# Converted to no-op migration - UUID conversion already handled by migration 0005

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration - UUID conversion already handled by migration 0005.

    This migration was automatically generated by Django when it detected
    a potential state mismatch, but the Configuration model's id field
    was already converted to UUIDField in migration 0005_configuration_uuid_proper.

    Migration 0005 performs the complete conversion from BigAutoField to UUIDField
    including both database schema changes and Django state updates. This migration
    is kept for historical migration chain integrity but performs no operations.

    See also:
    - 0005_configuration_uuid_proper.py - Complete UUID conversion implementation
    - 0006_alter_configuration_id_alter_configuration_value.py - Previous no-op migration
    - docs/fixes/test-database-migration-duplicate-column-rca-2025-10-20.md - RCA
    """

    dependencies = [
        ("core", "0008_alter_configuration_value"),
    ]

    operations = [
        # No operations needed - migration 0005 already handles UUID conversion
    ]
