# Generated by Django 5.1.13 on 2026-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_fix_configuration_id_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
