"""Custom template tags for SearchQuery and PIC framework rendering."""

from django import template
from django.utils.html import format_html
from django.utils.safestring import mark_safe

register = template.Library()


@register.filter
def pic_badge(component: str, component_type: str) -> str:
    """Render a badge for PIC framework components."""
    if not component or not component.strip():
        return format_html(
            '<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-secondary text-muted-foreground">Not specified</span>'
        )

    # Tailwind semantic colour mappings
    colors = {
        "population": "bg-primary text-primary-foreground",
        "interest": "bg-success text-white",
        "context": "bg-primary/80 text-primary-foreground",
    }

    color = colors.get(component_type.lower(), "bg-secondary text-secondary-foreground")
    short_text = component[:30] + "..." if len(component) > 30 else component

    return format_html(
        '<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {} text-wrap" title="{}">{}</span>',
        color,
        component,
        short_text,
    )


@register.filter
def keyword_list(keywords: list, max_display: int = 5) -> str:
    """Render a list of keywords with badges."""
    if not keywords:
        return '<span class="text-muted-foreground">None</span>'

    displayed = keywords[:max_display]
    remaining = len(keywords) - max_display

    html_parts = []
    for keyword in displayed:
        html_parts.append(
            format_html(
                '<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-secondary text-foreground mr-1">{}</span>',
                keyword,
            )
        )

    if remaining > 0:
        html_parts.append(
            format_html(
                '<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-muted text-muted-foreground">+{} more</span>',
                remaining,
            )
        )

    # SECURITY: Safe -- all parts generated by format_html() which escapes user input
    return mark_safe(" ".join(html_parts))  # nosec B703, B308


@register.filter
def search_engines_badges(engines: list) -> str:
    """Render badges for search engines."""
    if not engines:
        return '<span class="text-muted-foreground">None specified</span>'

    # Tailwind semantic colour mappings
    engine_colors = {
        "google": "bg-primary text-primary-foreground",
        "bing": "bg-primary/80 text-primary-foreground",
        "duckduckgo": "bg-success text-white",
        "yahoo": "bg-warning text-white",
    }

    badges = []
    for engine in engines:
        color = engine_colors.get(
            engine.lower(), "bg-secondary text-secondary-foreground"
        )
        badges.append(
            format_html(
                '<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {} mr-1">{}</span>',
                color,
                engine.title(),
            )
        )

    # SECURITY: Safe -- all parts generated by format_html() which escapes user input
    return mark_safe("".join(badges))  # nosec B703, B308


@register.filter
def highlight_placeholders(template_text: str) -> str:
    """Highlight placeholders in template text."""
    if not template_text:
        return ""

    import re

    def replace_placeholder(match):
        placeholder = match.group(1)
        return format_html(
            '<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-primary text-primary-foreground">{{{}}}</span>',
            placeholder,
        )

    highlighted = re.sub(r"\{([^}]+)\}", replace_placeholder, template_text)
    # SECURITY: Safe -- placeholders escaped by format_html()
    return mark_safe(highlighted)  # nosec B703, B308


@register.filter
def truncate_query(query_string: str, max_length: int = 100) -> str:
    """Truncate query string for display."""
    if not query_string:
        return ""

    if len(query_string) <= max_length:
        return query_string

    truncated = query_string[:max_length].rsplit(" ", 1)[0]
    return f"{truncated}..."
