import { Page, Locator, expect } from '@playwright/test';

/**
 * Auth Page Object
 *
 * Encapsulates login, signup, password reset, and profile page interactions.
 */
export class AuthPage {
  readonly page: Page;

  // Login page elements
  readonly usernameInput: Locator;
  readonly passwordInput: Locator;
  readonly loginButton: Locator;
  readonly signupLink: Locator;
  readonly forgotPasswordLink: Locator;
  readonly errorMessage: Locator;

  // Signup page elements (form has email + password only; username is auto-generated)
  readonly signupEmailInput: Locator;
  readonly signupPassword1Input: Locator;
  readonly signupPassword2Input: Locator;
  readonly signupButton: Locator;
  readonly loginLink: Locator;

  // Password reset elements
  readonly resetEmailInput: Locator;
  readonly resetSubmitButton: Locator;
  readonly backToLoginLink: Locator;

  constructor(page: Page) {
    this.page = page;

    // Login page
    this.usernameInput = page.locator('[data-testid="email"]');
    this.passwordInput = page.locator('[data-testid="password"]');
    this.loginButton = page.locator('[data-testid="login-btn"]');
    this.signupLink = page.locator('[data-testid="link-signup"], a[href*="signup"]');
    this.forgotPasswordLink = page.locator('[data-testid="link-forgot-password"], a[href*="password-reset"]');
    this.errorMessage = page.locator('[data-testid="error-message"], .alert-danger, .text-destructive, [role="alert"]:not([data-testid="feedback-toast"])');

    // Signup page (email + password only; username auto-generated by backend)
    this.signupEmailInput = page.locator('[data-testid="input-email"], #id_email');
    this.signupPassword1Input = page.locator('[data-testid="input-password1"], #id_password1');
    this.signupPassword2Input = page.locator('[data-testid="input-password2"], #id_password2');
    this.signupButton = page.locator('[data-testid="submit-signup-btn"]');
    this.loginLink = page.locator('[data-testid="link-login"], a[href*="login"]');

    // Password reset
    this.resetEmailInput = page.locator('[data-testid="input-email"], #id_email');
    this.resetSubmitButton = page.locator('[data-testid="submit-reset-btn"]');
    this.backToLoginLink = page.locator('[data-testid="link-back-login"], a[href*="login"]');
  }

  async goToLogin(): Promise<void> {
    await this.page.goto('/accounts/login/');
    await this.page.waitForLoadState('networkidle');
  }

  async goToSignup(): Promise<void> {
    await this.page.goto('/accounts/signup/');
    await this.page.waitForLoadState('networkidle');
  }

  async goToPasswordReset(): Promise<void> {
    await this.page.goto('/accounts/password-reset/');
    await this.page.waitForLoadState('networkidle');
  }

  async goToProfile(): Promise<void> {
    await this.page.goto('/accounts/profile/');
    await this.page.waitForLoadState('networkidle');
  }

  async expectOnLoginPage(): Promise<void> {
    await expect(this.page).toHaveURL(/\/accounts\/login\//);
    await expect(this.loginButton).toBeVisible();
  }

  async expectOnSignupPage(): Promise<void> {
    await expect(this.page).toHaveURL(/\/accounts\/signup\//);
    await expect(this.signupButton).toBeVisible();
  }

  async expectOnPasswordResetPage(): Promise<void> {
    await expect(this.page).toHaveURL(/\/accounts\/password-reset\//);
    await expect(this.resetSubmitButton).toBeVisible();
  }

  async expectOnPasswordResetDonePage(): Promise<void> {
    await expect(this.page).toHaveURL(/\/accounts\/password-reset\/done\//);
  }

  async expectOnDashboard(): Promise<void> {
    await expect(this.page).toHaveURL('/');
  }

  async expectError(): Promise<void> {
    await expect(this.errorMessage.first()).toBeVisible();
  }

  async login(username: string, password: string): Promise<void> {
    await this.goToLogin();
    await this.usernameInput.fill(username);
    await this.passwordInput.fill(password);
    await this.loginButton.click();
  }

  async loginAndExpectSuccess(username: string, password: string): Promise<void> {
    await this.login(username, password);
    await this.page.waitForURL(/\/(dashboard|sessions|$)/, { timeout: 15000 });
  }

  async loginAndExpectError(username: string, password: string): Promise<void> {
    await this.login(username, password);
    await this.expectOnLoginPage();
    await this.expectError();
  }

  async signup(data: {
    email: string;
    password: string;
  }): Promise<void> {
    await this.goToSignup();
    await this.signupEmailInput.fill(data.email);
    await this.signupPassword1Input.fill(data.password);
    await this.signupPassword2Input.fill(data.password);
    await this.signupButton.click();
  }

  async signupAndExpectSuccess(data: {
    email: string;
    password: string;
  }): Promise<void> {
    await this.signup(data);
    await this.page.waitForURL(/\/(dashboard|sessions|$)/, { timeout: 15000 });
  }

  async requestPasswordReset(email: string): Promise<void> {
    await this.goToPasswordReset();
    await this.resetEmailInput.fill(email);
    await this.resetSubmitButton.click();
    await this.expectOnPasswordResetDonePage();
  }

  async logout(): Promise<void> {
    await this.page.goto('/accounts/logout/');
    await this.page.waitForURL(/\/(accounts\/login\/)?$/, { timeout: 10000 });
  }

  async clickSignupLink(): Promise<void> {
    await this.signupLink.click();
    await this.expectOnSignupPage();
  }

  async clickLoginLink(): Promise<void> {
    await this.loginLink.click();
    await this.expectOnLoginPage();
  }

  async clickForgotPasswordLink(): Promise<void> {
    await this.forgotPasswordLink.click();
    await this.expectOnPasswordResetPage();
  }

  async clickBackToLoginLink(): Promise<void> {
    await this.backToLoginLink.click();
    await this.expectOnLoginPage();
  }
}
