# Generated by Django 4.2.11 on 2025-09-07 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userfeedback",
            new_name="feedback_us_created_25f00a_idx",
            old_name="feedback_us_created_4c7c68_idx",
        ),
        migrations.RenameIndex(
            model_name="userfeedback",
            new_name="feedback_us_page_pa_b668bf_idx",
            old_name="feedback_us_page_pa_0e1e4a_idx",
        ),
        migrations.RenameIndex(
            model_name="userfeedback",
            new_name="feedback_us_feedbac_9e8149_idx",
            old_name="feedback_us_feedbac_c8a42c_idx",
        ),
        migrations.RenameIndex(
            model_name="userfeedback",
            new_name="feedback_us_status_671e5b_idx",
            old_name="feedback_us_status_1f3c56_idx",
        ),
        migrations.RenameIndex(
            model_name="userfeedback",
            new_name="feedback_us_user_id_819323_idx",
            old_name="feedback_us_user_id_9c7b47_idx",
        ),
    ]
