# Generated by Django 5.1.13 on 2026-02-22 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "feedback",
            "0002_rename_feedback_us_created_4c7c68_idx_feedback_us_created_25f00a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
