# Generated by Django 5.1.13 on 2026-02-22 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "feedback",
            "0003_alter_userfeedback_created_at_alter_userfeedback_id_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedbackStatistics",
        ),
    ]
