# Generated by Django 5.1.13 on 2026-03-17 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_remove_feedbackstatistics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedback",
            name="actual_behaviour",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="audio_duration_ms",
            field=models.PositiveIntegerField(
                blank=True, help_text="Recording duration in milliseconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to="feedback/audio/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="expected_behaviour",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("always", "Always"),
                    ("sometimes", "Sometimes"),
                    ("once", "Once"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="github_issue_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="github_issue_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="github_issue_resolution",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="github_issue_state",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="github_issue_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="interaction_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="pages_visited, recent_clicks, js_errors",
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="screen_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-categorised from page_path",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="feedback/screenshots/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("must_have", "Must Have"),
                    ("should_have", "Should Have"),
                    ("nice_to_have", "Nice To Have"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="team_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("deferred", "Deferred"),
                    ("completed", "Completed"),
                    ("duplicate", "Duplicate"),
                    ("needs_info", "Needs Info"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="team_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="team_decision_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="transcription",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Transcribed text from voice recording",
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="voice_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="recording_stopped_by, transcription_service, confidence",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("bug", "Bug Report"),
                    ("idea", "Feature Idea"),
                    ("suggestion", "Suggestion"),
                    ("general", "General Feedback"),
                ],
                default="general",
                help_text="Category of feedback",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(
                fields=["severity"], name="feedback_us_severit_10767d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(
                fields=["team_decision"], name="feedback_us_team_de_c13a5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(
                fields=["github_issue_number"], name="feedback_us_github__466740_idx"
            ),
        ),
    ]
