# Generated by Django 4.2.11 on 2025-08-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchexecution",
            name="celery_task_id",
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                help_text="Celery task ID for async execution",
            ),
        ),
    ]
