# Generated by Django 4.2.11 on 2025-08-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0002_allow_null_celery_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawsearchresult",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Complete raw response from API"
            ),
        ),
        migrations.AlterField(
            model_name="searchexecution",
            name="api_parameters",
            field=models.JSONField(
                blank=True, default=dict, help_text="Parameters sent to the API"
            ),
        ),
    ]
