# Generated by Django 4.2.11 on 2025-08-24 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0004_add_api_result_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexecution",
            name="current_step",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current execution step description",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="searchexecution",
            name="processing_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initializing", "Initializing"),
                    ("querying", "Querying API"),
                    ("parsing", "Parsing Results"),
                    ("storing", "Storing Results"),
                    ("finalizing", "Finalizing"),
                ],
                default="initializing",
                help_text="Current processing phase",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="searchexecution",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                help_text="Execution progress percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="searchexecution",
            name="step_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Detailed step tracking data"
            ),
        ),
    ]
