# Generated by Django 4.2.11 on 2025-08-26 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0005_searchexecution_current_step_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchexecution",
            name="progress_percentage",
        ),
    ]
