# Generated by Django 4.2.11 on 2025-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0006_remove_progress_percentage_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawsearchresult",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete raw response from API. See RawDataType in model_types.py",
            ),
        ),
        migrations.AlterField(
            model_name="searchexecution",
            name="api_parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parameters sent to the API. See APIParametersType in model_types.py",
            ),
        ),
        migrations.AlterField(
            model_name="searchexecution",
            name="step_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed step tracking data. See StepMetadataType in model_types.py",
            ),
        ),
    ]
