# Generated by Django 5.1.13 on 2026-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0007_alter_rawsearchresult_raw_data_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rawsearchresult",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="rawsearchresult",
            constraint=models.UniqueConstraint(
                fields=("execution", "position"), name="unique_execution_position"
            ),
        ),
    ]
