# Generated by Django 5.1.13 on 2026-02-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0008_alter_rawsearchresult_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexecution",
            name="execution_round",
            field=models.IntegerField(
                default=1,
                help_text="Which iteration of the search strategy produced this execution (1-based)",
            ),
        ),
        migrations.AddField(
            model_name="searchexecution",
            name="strategy_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of the search strategy at time of execution",
            ),
        ),
    ]
