# Generated by Django 5.1.13 on 2026-02-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0009_add_execution_round_and_strategy_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexecution",
            name="serp_provider",
            field=models.CharField(
                db_index=True,
                default="serper",
                help_text="SERP API provider key used for this execution (e.g., serper, serpapi)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="searchexecution",
            name="serp_provider_display",
            field=models.CharField(
                default="Serper.dev",
                help_text="Human-readable provider name at time of execution",
                max_length=100,
            ),
        ),
    ]
