# Generated by Django 5.1.13 on 2026-02-24 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0006_remove_redundant_token_index"),
        ("serp_execution", "0010_add_serp_provider_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerpProviderConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_key",
                    models.CharField(
                        help_text="Internal key (e.g. 'serper', 'serpapi', 'scaleserp')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g. 'Serper.dev')",
                        max_length=100,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="Base API URL for this provider"),
                ),
                (
                    "api_key_setting",
                    models.CharField(
                        blank=True,
                        help_text="Django settings key for API key (e.g. 'SERPER_API_KEY')",
                        max_length=100,
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(
                        default=100,
                        help_text="Max requests per minute for this provider",
                    ),
                ),
                (
                    "rate_limit_burst",
                    models.IntegerField(
                        default=10, help_text="Burst allowance for rate limiting"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the system-wide default provider",
                    ),
                ),
                (
                    "max_results_per_query",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum results this provider can return per query",
                    ),
                ),
                ("supports_pagination", models.BooleanField(default=True)),
                (
                    "supported_search_engines",
                    models.JSONField(
                        default=list,
                        help_text="List of search engines supported (e.g. ['google', 'bing'])",
                    ),
                ),
                (
                    "default_for_organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this config is the org-level default",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serp_provider_configs",
                        to="organisation.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "serp_provider_configs",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="unique_default_provider",
                    )
                ],
            },
        ),
    ]
