# Generated by Django 5.1.13 on 2026-02-24 16:20

from django.db import migrations


def seed_serper_provider(apps, schema_editor):
    """Seed Serper.dev as the default SERP provider."""
    SerpProviderConfig = apps.get_model("serp_execution", "SerpProviderConfig")
    SerpProviderConfig.objects.get_or_create(
        provider_key="serper",
        defaults={
            "display_name": "Serper.dev",
            "base_url": "https://google.serper.dev/search",
            "api_key_setting": "SERPER_API_KEY",
            "rate_limit_per_minute": 100,
            "rate_limit_burst": 10,
            "is_enabled": True,
            "is_default": True,
            "max_results_per_query": 100,
            "supports_pagination": True,
            "supported_search_engines": ["google"],
        },
    )


def reverse_seed(apps, schema_editor):
    """Remove the seeded Serper.dev provider."""
    SerpProviderConfig = apps.get_model("serp_execution", "SerpProviderConfig")
    SerpProviderConfig.objects.filter(provider_key="serper").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0011_create_serp_provider_config"),
    ]

    operations = [
        migrations.RunPython(seed_serper_provider, reverse_seed),
    ]
