# Generated by Django 5.1.13 on 2026-02-24 16:55

from django.db import migrations


def seed_searchapi_bing(apps, schema_editor):
    """Seed SearchAPI.io Bing as a secondary SERP provider."""
    SerpProviderConfig = apps.get_model("serp_execution", "SerpProviderConfig")
    SerpProviderConfig.objects.get_or_create(
        provider_key="searchapi_bing",
        defaults={
            "display_name": "SearchAPI.io (Bing)",
            "base_url": "https://www.searchapi.io/api/v1/search",
            "api_key_setting": "SEARCHAPI_API_KEY",
            "rate_limit_per_minute": 30,
            "rate_limit_burst": 5,
            "is_enabled": True,
            "is_default": False,
            "max_results_per_query": 50,
            "supports_pagination": True,
            "supported_search_engines": ["bing"],
        },
    )


def reverse_seed(apps, schema_editor):
    SerpProviderConfig = apps.get_model("serp_execution", "SerpProviderConfig")
    SerpProviderConfig.objects.filter(provider_key="searchapi_bing").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("serp_execution", "0012_seed_serper_provider_config"),
    ]

    operations = [
        migrations.RunPython(seed_searchapi_bing, reverse_seed),
    ]
