# Generated by Django 4.2.11 on 2025-08-13 15:16

from django.db import migrations, models


def ensure_is_active_field(apps, schema_editor):
    """
    Ensure the is_active field exists on SearchQuery model.
    This is a data migration to fix production issues where the field might be missing.
    """
    SearchQuery = apps.get_model("search_strategy", "SearchQuery")
    db_alias = schema_editor.connection.alias

    # Check if any SearchQuery records exist without is_active set
    queries_without_active = SearchQuery.objects.using(db_alias).filter(
        is_active__isnull=True
    )
    if queries_without_active.exists():
        # Set default value for existing records
        queries_without_active.update(is_active=True)
        print(
            f"Updated {queries_without_active.count()} SearchQuery records with is_active=True"
        )


def reverse_ensure_is_active_field(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("search_strategy", "0003_remove_querytemplate"),
    ]

    operations = [
        # Ensure the field exists (no-op if it already does)
        migrations.AlterField(
            model_name="searchquery",
            name="is_active",
            field=models.BooleanField(default=True, db_index=True),
        ),
        # Run the data migration to ensure all records have the field set
        migrations.RunPython(
            ensure_is_active_field,
            reverse_ensure_is_active_field,
        ),
    ]
