# Generated by Django 4.2.11 on 2025-08-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_strategy", "0004_ensure_is_active_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchquery",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
