# Generated by Django 4.2.7 on 2025-08-14

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def populate_session_field(apps, schema_editor):
    """
    Ensure all SearchQuery records have their denormalized session field populated.
    This fixes any records where session might be null but strategy.session exists.
    """
    SearchQuery = apps.get_model("search_strategy", "SearchQuery")

    # Update any SearchQuery records where session is null but strategy has a session
    queries_to_update = SearchQuery.objects.filter(
        session__isnull=True, strategy__session__isnull=False
    )

    for query in queries_to_update:
        query.session = query.strategy.session
        query.save(update_fields=["session"])

    updated_count = queries_to_update.count()
    if updated_count > 0:
        logger.info(
            f"Migration 0006: Updated {updated_count} SearchQuery records "
            f"with denormalised session field"
        )


def reverse_populate_session_field(apps, schema_editor):
    """
    Reverse operation - we don't actually want to undo this fix,
    so this is a no-op.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("search_strategy", "0005_alter_searchquery_is_active"),
    ]

    operations = [
        migrations.RunPython(populate_session_field, reverse_populate_session_field),
    ]
