# Generated by Django 4.2.11 on 2025-08-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_strategy", "0006_populate_searchquery_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="formatted_query",
            field=models.CharField(
                blank=True,
                help_text="User-friendly formatted query for display",
                max_length=500,
            ),
        ),
    ]
