# Generated by Django 4.2.11 on 2025-09-04 15:29

from django.db import migrations, models

import apps.search_strategy.models


class Migration(migrations.Migration):
    dependencies = [
        ("search_strategy", "0007_add_formatted_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchstrategy",
            name="search_config",
            field=models.JSONField(
                blank=True,
                default=apps.search_strategy.models.default_search_config,
                help_text="Configuration for domains, file types, and search parameters. See SearchConfigType in model_types.py",
            ),
        ),
        migrations.AlterField(
            model_name="searchstrategy",
            name="validation_errors",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validation error messages. See ValidationErrorsType in model_types.py",
            ),
        ),
    ]
