"""
Service for importing offline backup Excel files and syncing changes.

This module implements Excel import functionality to sync offline review
changes back to the database, validating data integrity and handling errors.
"""

import logging
from typing import Dict, List
from uuid import UUID

from django.core.exceptions import ValidationError
from django.db import transaction
from openpyxl import load_workbook  # type: ignore[reportMissingModuleSource]

from apps.results_manager.providers import get_results_provider
from apps.review_results.models import SimpleReviewDecision

logger = logging.getLogger(__name__)


class ExcelImportService:
    """Handle Excel import and database sync operations."""

    # Expected column order from export (after 2025-10-17 reordering)
    EXPECTED_COLUMNS = [
        "Title",
        "Snippet",
        "Search Date",
        "Review Decision",
        "Exclusion Reason",
        "Notes",
        "Search Query(ies)",
        "URL",
    ]

    VALID_DECISIONS = ["Include", "Exclude", "Maybe", ""]

    def import_excel_backup(self, session_id: str, excel_file, reviewer=None) -> Dict:
        """
        Import Excel backup and sync changes to database.

        Args:
            session_id: UUID of session to import into
            excel_file: Uploaded Excel file object (file-like)
            reviewer: User instance performing the import (optional)

        Returns:
            dict: Import summary with keys:
                - total_changes: int, number of detected changes
                - updated: int, successfully updated records
                - errors: int, failed updates
                - error_details: list of error dictionaries

        Raises:
            ExcelImportError: If import fails due to validation or processing errors
        """
        try:
            logger.info(f"Starting Excel import for session {session_id}")

            # Parse workbook
            wb = load_workbook(excel_file, data_only=True)

            # Validate structure
            self._validate_workbook_structure(wb)

            # Extract review data
            review_data = self._extract_review_data(wb)
            logger.info(f"Extracted {len(review_data)} rows from Excel")

            # Match with database records and detect changes
            changes = self._detect_changes(session_id, review_data)
            logger.info(f"Detected {len(changes)} changes to apply")

            # Apply changes in transaction
            summary = self._apply_changes(session_id, changes, reviewer=reviewer)

            logger.info(
                f"Excel import completed for session {session_id}: "
                f"{summary['updated']} updated, {summary['errors']} errors"
            )

            return summary

        except ValidationError as e:
            logger.error(
                f"Validation error during import for session {session_id}: {e}"
            )
            raise ExcelImportError(f"Import validation failed: {str(e)}")
        except Exception as e:
            logger.exception(f"Excel import failed for session {session_id}")
            raise ExcelImportError(f"Import failed: {str(e)}")

    def _validate_workbook_structure(self, wb) -> None:
        """
        Validate Excel workbook has expected structure.

        Args:
            wb: openpyxl Workbook instance

        Raises:
            ValidationError: If workbook structure is invalid
        """
        # Check required sheets
        if "Review Results" not in wb.sheetnames:
            raise ValidationError(
                "Missing 'Review Results' sheet. "
                "Please upload an offline backup file generated by Agent Grey."
            )

        ws = wb["Review Results"]

        # Check headers
        headers = [cell.value for cell in ws[1]]
        if headers != self.EXPECTED_COLUMNS:
            # Provide helpful error message
            missing = set(self.EXPECTED_COLUMNS) - set(headers)
            extra = set(headers) - set(self.EXPECTED_COLUMNS)

            error_parts = ["Column headers don't match expected format."]
            if missing:
                error_parts.append(f"Missing columns: {', '.join(missing)}")
            if extra:
                error_parts.append(f"Unexpected columns: {', '.join(extra)}")

            raise ValidationError(" ".join(error_parts))

        logger.debug("Workbook structure validation passed")

    def _extract_review_data(self, wb) -> List[Dict]:
        """
        Extract review decisions from Excel sheet.

        Args:
            wb: openpyxl Workbook instance

        Returns:
            List of dictionaries with keys:
                - title: str
                - url: str
                - decision: str
                - exclusion_reason: str
                - notes: str
        """
        ws = wb["Review Results"]
        review_data = []

        # Skip header row (row 1)
        for row_idx, row in enumerate(
            ws.iter_rows(min_row=2, values_only=True), start=2
        ):
            title, snippet, search_date, decision, reason, notes, queries, url = row

            # Skip empty rows
            if not title and not url:
                continue

            # Normalize decision (capitalize first letter to match dropdown values)
            if decision:
                decision = str(decision).strip().capitalize()
            else:
                decision = ""

            # Validate decision
            if decision and decision not in self.VALID_DECISIONS:
                logger.warning(
                    f"Invalid decision '{decision}' in row {row_idx} for result: {title}. "
                    f"Valid options: {', '.join(self.VALID_DECISIONS)}"
                )
                decision = ""

            review_data.append(
                {
                    "title": title,
                    "url": url,
                    "decision": decision.lower()
                    if decision
                    else "",  # Store as lowercase
                    "exclusion_reason": str(reason).strip() if reason else "",
                    "notes": str(notes).strip() if notes else "",
                }
            )

        return review_data

    def _detect_changes(self, session_id: str, review_data: List[Dict]) -> List[Dict]:
        """
        Compare Excel data with database and detect changes.

        Args:
            session_id: UUID of session
            review_data: List of review data dictionaries from Excel

        Returns:
            List of change dictionaries with keys:
                - result_id: UUID of ProcessedResult
                - old_values: dict with current database values
                - new_values: dict with values from Excel
        """
        results_provider = get_results_provider()
        results = results_provider.get_results_for_session(UUID(session_id))

        # Get existing decisions in bulk to avoid N+1 queries
        existing_decisions = {
            str(d.result_id): d
            for d in SimpleReviewDecision.objects.filter(
                result__session_id=session_id
            ).select_related("result")
        }

        changes = []

        for result in results:  # type: ignore[reportGeneralTypeIssues]
            # Match by title and URL (unique identifier)
            excel_row = self._find_matching_row(result, review_data)
            if not excel_row:
                logger.debug(f"No match found in Excel for result: {result.id}")
                continue

            existing = existing_decisions.get(str(result.id))

            # Get current values
            old_decision = existing.decision if existing else ""
            old_reason = existing.exclusion_reason if existing else ""
            old_notes = existing.notes if existing else ""

            # Get new values from Excel
            new_decision = excel_row["decision"]
            new_reason = excel_row["exclusion_reason"]
            new_notes = excel_row["notes"]

            # Check for changes
            if (
                old_decision != new_decision
                or old_reason != new_reason
                or old_notes != new_notes
            ):
                changes.append(
                    {
                        "result_id": result.id,
                        "old_values": {
                            "decision": old_decision,
                            "exclusion_reason": old_reason,
                            "notes": old_notes,
                        },
                        "new_values": {
                            "decision": new_decision,
                            "exclusion_reason": new_reason,
                            "notes": new_notes,
                        },
                    }
                )

        return changes

    def _find_matching_row(self, result, review_data: List[Dict]) -> Dict | None:
        """
        Find Excel row matching a database result.

        Args:
            result: ProcessedResult instance
            review_data: List of review data dictionaries from Excel

        Returns:
            Dictionary with review data if match found, None otherwise
        """
        for row in review_data:
            # Match by both title and URL for accuracy
            if row["title"] == result.title and row["url"] == result.url:
                return row
        return None

    @transaction.atomic
    def _apply_changes(
        self, session_id: str, changes: List[Dict], reviewer=None
    ) -> Dict:
        """
        Apply changes to database in atomic transaction.

        Args:
            session_id: UUID of session
            changes: List of change dictionaries
            reviewer: User instance (optional, for reviewer field)

        Returns:
            Dictionary with keys:
                - total_changes: int
                - updated: int
                - errors: int
                - error_details: list of error dictionaries
        """
        from apps.results_manager.models import ProcessedResult
        from apps.review_manager.models import SearchSession

        # Get session for denormalized field
        try:
            session = SearchSession.objects.get(id=session_id)
        except SearchSession.DoesNotExist:
            return {
                "total_changes": len(changes),
                "updated": 0,
                "errors": len(changes),
                "error_details": [{"error": "Session not found"}],
            }

        updated_count = 0
        error_count = 0
        errors = []

        for change in changes:
            try:
                result_id = change["result_id"]
                new_vals = change["new_values"]

                # Get result to populate denormalized session field
                _result = ProcessedResult.objects.get(id=result_id)

                # Get or create decision with required fields
                decision, created = SimpleReviewDecision.objects.get_or_create(
                    result_id=result_id,
                    defaults={
                        "session": session,  # Required denormalized field
                        "reviewer": reviewer,  # May be None (allowed)
                        "decision": new_vals["decision"],
                        "exclusion_reason": new_vals["exclusion_reason"],
                        "notes": new_vals["notes"],
                    },
                )

                if not created:
                    # Update existing
                    decision.decision = new_vals["decision"]
                    decision.exclusion_reason = new_vals["exclusion_reason"]
                    decision.notes = new_vals["notes"]
                    if reviewer:
                        decision.reviewer = reviewer
                    decision.save()

                updated_count += 1

                # Log change for audit trail
                logger.info(
                    f"Updated review decision for result {result_id}: "
                    f"{change['old_values']['decision']} → {new_vals['decision']}"
                )

            except Exception as e:
                error_count += 1
                errors.append({"result_id": str(change["result_id"]), "error": str(e)})
                logger.error(f"Failed to update result {change['result_id']}: {e}")

        return {
            "total_changes": len(changes),
            "updated": updated_count,
            "errors": error_count,
            "error_details": errors,
        }


class ExcelImportError(Exception):
    """Custom exception for Excel import failures."""

    pass
